### ISSUE TITLE
Weird error dialog displayed when in mesh editor

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#101]
Starting with a new install of ICE, I selected the mesh editor from the toolbar. After a few seconds, I got the following dialog (truncated because it ran off my screen):

<img width="1425" alt="screen shot 2016-02-16 at 9 42 23 am" src="https://cloud.githubusercontent.com/assets/6130694/13081454/e7452f52-d49a-11e5-8e04-5fed89e41a51.png">

**Comment by SmithRWORNL** [comment]
@jarrah42 

Which version of ICE were you running? This error is coming from the LightWeight Java Game Library, which was used by the old jMonkeyEngine implementation of the mesh editor, but not shouldn't be referenced by the JavaFX implementation which is replacing it.

**Comment by amccaskey** [comment]
He found this on Master.

**Comment by SmithRWORNL** [comment]
Master hasn't had the JavaFX stuff pulled in, so it's definitely a JME3 issue. Closing this bug, since it relates to an implementation we no longer support.

**Comment by amccaskey** [comment]
Keep it open. We still technically support it since we have public binaries of master available.

**Comment by jayjaybillings** [comment]
I was looking at this some more. I haven't seen it before. We need to determine if it is related to 3D graphics drivers. I'm asking @jarrah42 about it.
