### ISSUE TITLE
The "Specify ICE Item parameters" window is too stark

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#114]
The "Specify ICE Item parameters" window has issues. First, "Class Base Name" is not sufficiently explanatory for new users. This should say something like "Item Class Name: " and it should have a tool tip with a description that fits what it is. Second, the work "parameters" in the title should be capitalized like the rest of the window. Third, a header that runs across the gray (lower) part of the text saying something like "Please configure these custom parameters for your ICE plugin" would help explain what this screen is for.

**Comment by jayjaybillings** [comment]
This window should also give me a choice of whether or not I want to generate a Model, a JobLauncher or a basic Item class. The basic Item should be disabled until they deselect both Model and JobLauncher.

**Comment by arbennett** [comment]
@jayjaybillings the wizard page now has toggles for Job Launcher and Model creation, but I'm a little bit unclear about what a basic Item would do.  I've also been thinking about if we could add an option to specify the "IO Format" with a drop down for all of the available IO services which would be used to get the Readers and Writers.

**Comment by jayjaybillings** [comment]
Sounds good.

For the basic Item, what if I want to create something that is neither a model nor a JobLauncher? It is more of an advanced use case I suppose.

For the IO Formats, that would be great!
