### ISSUE TITLE
Newly created Items are not immediately viewable and break ICE

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#118]
The newly generated Items created by the project generator do not include 

form = new Form();

in their setupForm() operations. This causes a null pointer exception at Item.java:532. 

Two things need to be fixed. First, all new setupForm() operations should include the line of code above. It is a rule that all newly created Items in ICE be launchable. (Check the docs.) Second, the Item needs to be updated to check the form to make sure it isn't null. The simplest way to fix this is to move the check for the action list into the if statement that checks if the form is null at line Item.java:537.

**Comment by jayjaybillings** [comment]
Note that putting this line of code in the file will require that the file also includes 

import org.eclipse.ice.datastructure.form.Form;

**Comment by arbennett** [comment]
Fixed as of 1505ea27d291af86611c0a70ccf6773f2ec7babb
