### ISSUE TITLE
Newly created Models do not extend Model and break ICE.

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#119]
The new project generator creates Models that do not extend Model.java, but instead extend Item.java. This in turn breaks ICE when ICE tries to load databases into the Model.

**Comment by jayjaybillings** [comment]
This will require importing Model.

import org.eclipse.ice.item.model.Model;

**Comment by arbennett** [comment]
Fixed as of 1505ea27d291af86611c0a70ccf6773f2ec7babb
