### ISSUE TITLE
Newly created Items with the Item project generator do not include names, descriptions, etc.

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#120]
Items that are created with the new plugin generator should include a human readable name and description, which can be set by calling setName(name) and setDescription(desc) from the setupItemInfo() operation. The same human readable name should be used in the Builder for this Item.

Failing to do this creates a bare-bones Item that looks like the attached picture in the Item selector. The name in the Item Selector is the name returned by the Builder because ICE's pulls all builder names and returns them to the client upon request for the viewer. 

![itemselectorwithfunkynames](https://cloud.githubusercontent.com/assets/6378849/13267545/de62a854-da4b-11e5-910d-6e450dc938c0.png)

This also ends up with the default name being shown in the Item Viewer, as shown below.

![itemviewershowingdefaultname](https://cloud.githubusercontent.com/assets/6378849/13267574/0207859a-da4c-11e5-862e-81b6f409b39a.png)

**Comment by arbennett** [comment]
This should have been fixed as of c2c034110710962a47b234915caa9ea043f03c79.  Tutorial materials will also explain how to customize these things beyond the defaults.
