### ISSUE TITLE
Newly created Items do not need to redeclare ioService

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#121]
Newly created Items that were generated with the project generator do not need to redeclare ioService as shown below. Developers can obtain that locally by calling the getIOService() operation on the base class.

Redeclaring the variable leads to scope problems and could result in null pointer exceptions.

**Comment by arbennett** [comment]
I think this was also referenced in #147, so I'm going to close it.  Feel free to open it again if I'm mistaken.
