### ISSUE TITLE
Newly created items should return a status from reviewEntries()

### ISSUE THREAD

**Issue by erwindl0** [eclipse/ice#123]
In the org.eclipse.ice.triquetrum.model.TriquetrumWorkflowItemModel, reviewEntries() returns null. 
If this is the case by default for generated item templates, the issues may occur as described below. I guess the reviewEntries() method should by default return a valid status, similar to what was mentioned in #122 ?

Related to this, a possible small improvement to avoid the NPEs that I saw : 
The NPEs were caused by comparing the form status similar to the following : 
`if (!status.equals(FormStatus.NeedsInfo))`
where status is null due to the above. 

It might be better to reverse the equals() order to something like : 
`if(!FormStatus.NeedsInfo.equals(status))`
i.e. put the constant/enum value first, which would avoid the NPEs.

-----

The resulting problems I encountered were :

When creating a new item instance in ICE, and entering a form entry value, the save action will fail with an NPE, shown both in an error dialog and in the logs :

!ENTRY org.eclipse.ui 2 0 2016-02-24 15:33:17.689
!MESSAGE Save Failed
!STACK 0
java.lang.NullPointerException
	at org.eclipse.ice.core.internal.itemmanager.ItemManager.updateItem(ItemManager.java:924)
	at org.eclipse.ice.core.internal.Core.updateItem(Core.java:487)
	at org.eclipse.ice.client.internal.Client.formUpdated(Client.java:601)
	at org.eclipse.ice.client.widgets.ICEFormEditor.notifyUpdateListeners(ICEFormEditor.java:1069)
	at org.eclipse.ice.client.widgets.ICEFormEditor.doSave(ICEFormEditor.java:710)

The item form still looses its dirty marker afterwards. When you close the form and try to reopen it by double-clicking the item in the Item Viewer, this fails again with an NPE : 

!ENTRY org.eclipse.jface 4 2 2016-02-24 15:34:55.333
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.ice.item.Item.getForm(Item.java:790)
	at org.eclipse.ice.core.internal.itemmanager.ItemManager.retrieveItem(ItemManager.java:315)
	at org.eclipse.ice.core.internal.Core.getItem(Core.java:448)
	at org.eclipse.ice.client.internal.Client.loadItem(Client.java:405)
	at org.eclipse.ice.client.common.ItemViewer$3.doubleClick(ItemViewer.java:195)

**Comment by jarrah42** [comment]
I see a lot of code with the constant first, e.g. "".equals(status), but IMHO this is just shifts the problem somewhere else. If status is able to be null, then there should be a null check and it should be properly dealt with before any other code is executed.

**Comment by erwindl0** [comment]
True, the main issue is probably that status should not be allowed to be null. E.g. by always ensuring a non-null status being returned from the reviewEntries() in this particular case.

**Comment by jayjaybillings** [comment]
Yes, the main issue is that Andrew just needs to return something like FormStatus.ReadyToSubmit or something by default instead of null.

**Comment by jayjaybillings** [comment]
I noticed this yesterday when I was working on the plugin but decided that ten bugs lumped on Andrew was enough for one day, but this is a new day. ;-)

**Comment by arbennett** [comment]
This was already fixed yesterday.

**Comment by jayjaybillings** [comment]
In next?

**Comment by arbennett** [comment]
Yep. In the following lines:

https://github.com/eclipse/ice/blob/next/org.eclipse.ice.projectgeneration/templates_3.4/ICEItem/src/%24className%24Model.java#L97-L104
