### ISSUE TITLE
Add Eclipse bundle signing

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#131]
ICE bundles need to be signed by Eclipse otherwise they show up as unsigned. Also, I think this is a requirement for graduation from Technology.

**Comment by jarrah42** [comment]
In order to enable signing, the build has to specify the "eclipse-sign" profile. For hudson, this is specified using the "Advanced" button on the "Invoke Maven 3" section.

I believe this can now be closed.

**Comment by jayjaybillings** [comment]
By that you mean that you check that box in the HIPP?

**Comment by jarrah42** [comment]
No, you have to click on the advanced button to display the advanced configuration section. Find the "Profiles" text box and you should see the extra profiles I added.

**Comment by jarrah42** [comment]
In the HIPP configuration, yes.
