### ISSUE TITLE
Sign the application for OS X

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#132]
Need to add OS X singing for the application to avoid nasty Gatekeeper messages.

**Comment by jayjaybillings** [comment]
We need to get signing going for all of our builds, not just OS X. Can you look into it for Linux and Windows too?

**Comment by jarrah42** [comment]
There are two kinds of signing, do you mean signing Eclipse bundles (Issue #131) or OS specific signing (e.g. required by OS X Gatekeeper)?

**Comment by jayjaybillings** [comment]
Both. Sorry!

I think this is closed, right? You just committed the fix?

**Comment by jarrah42** [comment]
I've committed a fix for #131, but not this one yet.

**Comment by jarrah42** [comment]
This is a duplicate of #106.
