### ISSUE TITLE
VisIt Preferences not available in latest unstable nightly

### ISSUE THREAD

**Issue by tcpatt** [eclipse/ice#136]
The unstable nightly builds of ICE for OS X, Linux, and Windows downloaded from eclipseice.ornl.gov do not include the page for Visualization > VisIt in the Preferences dialog. I found this in a build downloaded on 2016-02-25.

**Comment by SmithRWORNL** [comment]
@jayjaybillings 

Per our discussion, I finished refreshing the target, but still can't add the gov.lbnl.visit.swt package to the product.

**Comment by SmithRWORNL** [comment]
We had some bundles missing from the feature. Fixed by commit 914ef2ee5b9e87cf52c1e9c6ff07b19ff8557515.
