### ISSUE TITLE
Generated Items incorrectly assign exportString name in wrong place

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#149]
The value of exportString should not be set as follows:

```
	public DemoModel(IProject project) {
		super(project);
		exportString = "Export to Demo input format";

		// TODO: (optional) Add User Code Here
	}
```

The problem is that exportString will be null until after the super constructor is called. This means that when Item.setupItemInfo() is called to add exportString to the list allowed actions, it will add a null value to the list.

This should just be set in Item.setupItemInfo() as such:

```
	@Override
	protected void setupItemInfo() {
		setName("Demo Model");
		setDescription("Specify information about Demo");
		exportString = "Export to Demo input format";
		allowedActions.add(0, exportString);
	}
```

**Comment by erwindl0** [comment]
Jay, all,

"super"-constructor chains are indeed brittle if a base-class 
constructor depends on state/readiness of stuff in a subclass, or when 
it invokes methods that must be implemented in subclasses. This 
structure forces developers to be aware of this fact, and to think about 
where to put property initialization etc as Jay mentions.

If it's the case that Items are always constructed via their builder, 
could it be an option to split basic Item construction from further 
initialisation?
E.g. all the setup... methods etc could be invoked in a second step 
inside the builder.getInstance() ?
E.g. for the Triquetrum trial :

     public Item getInstance(IProject projectSpace) {
         Item item = new TriquetrumWorkflowItemModel(projectSpace);
         item.setItemBuilderName(this.getItemName());
*item.init(); // or setup() or some similar name*
         return item;
     }

Is that an option, or are Item instances created directly as well, 
without using the builders?
(in which case adding a separate init() method would put a burden on 
application developers who would need to add it all over their code when 
creating items, and it might not be a good idea then)

cheers
erwin

Op 01/03/2016 om 04:27 schreef Jay Jay Billings:

**Comment by jayjaybillings** [comment]
Erwin,

You are right of course!

The Item class is very old and in need of an extensive overhaul, including breaking the chained constructors. This is on my list of future tasks, so maybe I'll clean it up this summer. Basically everything in Item() should move into the AbstractItemBuilder class.

Jay

From my phone.
________________________________
From: erwin de ley
Sent: Tuesday, March 1, 2016 6:58 AM
To: eclipse/ice
CC: "Billings, Jay Jay"
Subject: Re: [ice] Generated Items incorrectly assign exportString name in wrong place (#149)


Jay, all,

"super"-constructor chains are indeed brittle if a base-class
constructor depends on state/readiness of stuff in a subclass, or when
it invokes methods that must be implemented in subclasses. This
structure forces developers to be aware of this fact, and to think about
where to put property initialization etc as Jay mentions.

If it's the case that Items are always constructed via their builder,
could it be an option to split basic Item construction from further
initialisation?
E.g. all the setup... methods etc could be invoked in a second step
inside the builder.getInstance() ?
E.g. for the Triquetrum trial :

public Item getInstance(IProject projectSpace) {
Item item = new TriquetrumWorkflowItemModel(projectSpace);
item.setItemBuilderName(this.getItemName());
*item.init(); // or setup() or some similar name*
return item;
}

Is that an option, or are Item instances created directly as well,
without using the builders?
(in which case adding a separate init() method would put a burden on
application developers who would need to add it all over their code when
creating items, and it might not be a good idea then)

cheers
erwin

Op 01/03/2016 om 04:27 schreef Jay Jay Billings:
>
> The value of exportString should not be set as follows:
>
> |public DemoModel(IProject project) { super(project); exportString =
> "Export to Demo input format"; // TODO: (optional) Add User Code Here } |
>
> The problem is that exportString will be null until after the super
> constructor is called. This means that when Item.setupItemInfo() is
> called to add exportString to the list allowed actions, it will add a
> null value to the list.
>
> This should just be set in Item.setupItemInfo() as such:
>
> |@Override protected void setupItemInfo() { setName("Demo Model");
> setDescription("Specify information about Demo"); exportString =
> "Export to Demo input format"; allowedActions.add(0, exportString); } |
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipse/ice/issues/149>.
>


-
