### ISSUE TITLE
Add PyDev to ICE

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#154]

**Comment by jayjaybillings** [comment]
I don't know that we want to add PyDev to ICE for all builds. I'm not sure it would pass the CQ process. We at least need it for the the tutorial though.

Jay

From my phone.
________________________________
From: jarrah42
Sent: Tuesday, March 1, 2016 1:29 PM
To: eclipse/ice
Subject: [ice] Add PyDev to ICE (#154)



-

**Comment by jarrah42** [comment]
May be a good candidate for the developer menu?

**Comment by jayjaybillings** [comment]
That's a big +1, good buddy!

From my phone.
________________________________
From: jarrah42
Sent: Tuesday, March 1, 2016 3:23 PM
To: eclipse/ice
CC: "Billings, Jay Jay"
Subject: Re: [ice] Add PyDev to ICE (#154)



May be a good candidate for the developer menu?

-

**Comment by amccaskey** [comment]
I think that is cool. But doesn't that still leave the problem of the students having to download it in the tutorial?

**Comment by jayjaybillings** [comment]
Yes, for the tutorial we have to install it in the image and then recreate the zip files. Or we can copy the p2 file onto the usb sticks.

From my phone.
________________________________
From: Alex McCaskey
Sent: Tuesday, March 1, 2016 3:50 PM
To: eclipse/ice
CC: "Billings, Jay Jay"
Subject: Re: [ice] Add PyDev to ICE (#154)



I think that is cool. But doesn't that still leave the problem of the students having to download it in the tutorial?

-
