### ISSUE TITLE
Creating New ICE Item Project Errors

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#159]
Best way to show this is the attached screenshot. 
![screen shot 2016-03-02 at 3 04 56 pm](https://cloud.githubusercontent.com/assets/827531/13473667/5c461746-e088-11e5-9ef3-08ba4a09b698.png)

This is in next. Do we need this method? We shouldn't be switching on allowed value types with the new IEntry Refactor, the new IEntry does not use them.

**Comment by arbennett** [comment]
I'm not entirely familiar with the new IEntry.  How should this method look, or what would its replacement be?  This method was mostly added to make the tutorial simpler.

**Comment by amccaskey** [comment]
I would just show the addition of some Components/IEntries in the setupForm method, and get rid of that method. I would also separate setupForm from the loadInput method. 

```java
IEntry someEntry = new StringEntry();
someEntry.setName("Some Entry");

IEntry discreteEntry = new DiscreteEntry("val1", "val2", "val3");
discreteEntry.setName("Discrete Entry Name")

DataComponent comp = new DataComponent();
...
comp.addEntry(someEntry);
comp.addEntry(discreteEntry);
```

It might be good for the template to just comment the above lines out and have a note explaining how to create Components in ICE.
