### ISSUE TITLE
FileEntry does not update when workspace modified

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#166]
They FileEntry does not update its list of allowed values when the workspace is modified. This can be seen easily when using EASE scripts to run ICE and update values, as show below.

	org.eclipse.ease.modules.EnvironmentModule@7882a30e
// use help("<topic>") to get more information
include("workspace://org.eclipse.ice.examples.reflectivity/createAndProcessPython.py");
	InfoError
loadModule('/System/Platform')
	org.eclipse.ease.modules.platform.PlatformModule@5302572b
coreService = getService(org.eclipse.ice.core.iCore.ICore);
	[null]
reflectModel = coreService.getItem(int(coreService.createItem("Reflectivity Model")))
	[null]
component = reflectModel.getComponents().get(0)
	[null]
component.retrieveAllEntries().get(0)
	org.eclipse.ice.datastructures.entry.FileEntry@6cd9bdb
entry = component.retrieveAllEntries().get(0)
	[null]
entry.setValue("waveVector_space.csv")
	false
entry.getErrorMessage()
	'waveVector_space.csv' is an unacceptable value. The value must be one of Geometry_Editor_1_processOutput.txt, Reflectivity_Model.xml, or VIBE_Key-Value_Pair_1_processOutput.txt.

<Go import file to itemDB and then run the script below.>

entry.setValue("waveVector_space.csv")
	false
entry.getErrorMessage()
	'waveVector_space.csv' is an unacceptable value. The value must be one of Geometry_Editor_1_processOutput.txt, Reflectivity_Model.xml, or VIBE_Key-Value_Pair_1_processOutput.txt.

**Comment by jarrah42** [comment]
Did this need to be fixed for the tutorial?

**Comment by amccaskey** [comment]
Good catch. I've got a fix for this.
