### ISSUE TITLE
ResourceComponent Tutorial Errors

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#168]
The ResourceComponent Tutorial needs updating: 

AbstractView -> BasicView
ResourceComponent.add -> addResource

Also don't do project.getFile() in setupForm without checking that those files exist. This caused  a NPE that caused ICE Core to fail to load.

**Comment by SmithRWORNL** [comment]
Addressed in commit 6994bfaba7632a5cc7845cf3489261646fb2ee8e.

**Comment by amccaskey** [comment]
Robert, 

The check on the IFile's before your VizResource creations is not correct. project.getFile will return a valid IFile reference, even if the file doesn't exist. What you want to do is check csvFile.exists() instead of csvFile == null.

**Comment by SmithRWORNL** [comment]
Switched the check to use exists() in commit f5cb839e37b2dd5d7ae90b31ea4c96eb1b33de6e.
