### ISSUE TITLE
Replace Bison files in ICE tests with MOOSE Test files

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#172]
The Bison files in ICETests prevent us from releasing those files publicly. If possible, please replace them with files from MOOSE Test instead. Note that "if possible" means that similarly complicated MOOSE Test yaml and action syntax files with multiple blocks and a sophisticated tree can be obtained such that the level of test coverage is not compromised.

**Comment by jayjaybillings** [comment]
@amccaskey What's the status on this? Do you need a hand or anything?

**Comment by jayjaybillings** [comment]
@amccaskey Any chance you can tackle this one soon?

**Comment by amccaskey** [comment]
The bison files have been removed from ICETests, the tests have been updated in ICE next, and we will merge next into master in the next few days.
