### ISSUE TITLE
Installer should be updated to point to our new download site

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#173]
Our new download site is at eclipse.org:

https://projects.eclipse.org/projects/technology.ice/downloads

The installer should point to this.

**Comment by jayjaybillings** [comment]
@arbennett Will you look at this please?

**Comment by arbennett** [comment]
I'm looking at this, and have some concerns about it.  As it stands, updating the installer to use the eclipse.org download site will induce a certain amount of fragility.  It's mostly to do with naming conventions.  At eclipseice.ornl.gov we use `ice.product-linux.gtk.x86.zip`, and at projects.eclipse.org we use `ice-linux-gtk-x86-2.1.8.zip`.  There are a couple of notable differences,

1. One has a `.product` following `ice`
2. One uses `.` as a separator and one uses `-` as a separator
3. One has a version tag (`2.1.8`)

While it is certainly _possible_ to account for these differences when specifying the `--stable` vs `--unstable` downloads I think we would save ourselves some future headaches if we got the naming scheme to be consistent in at least (1) and (2) before going ahead with this.  I can handle (3) with a simple `VERSION` variable that can get set to `""` if they are trying to download from eclipseice.ornl.gov.  

@jayjaybillings what do you think about this?

**Comment by jayjaybillings** [comment]
I don't think it is an issue if @amccaskey fixes #192 before you fix this. You might ping him and see if he can knock that one out for you.

**Comment by arbennett** [comment]
Roger that.  I'll tackle this when #192 is fixed.  Thanks.

**Comment by jayjaybillings** [comment]
Well, don't just drop off! :-) Post a comment on #192 and then email @amccaskey to annoy him into fixing #192 for you. The squeaky gear gets the grease!

**Comment by amccaskey** [comment]
Working on it now. Wrote the script, running it through some tests.

**Comment by arbennett** [comment]
This has been fixed.
