### ISSUE TITLE
Eclipse download page should point to master, not next

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#174]
The download page for ICE points to the next build, which is unstable.

http://download.eclipse.org/ice/builds/next/

The master build should be exported to our downloads directory and the download page should point to it instead.

**Comment by jayjaybillings** [comment]
We actually need both next and master update sites. Sorry, I should have been clear about that.

**Comment by jayjaybillings** [comment]
@jarrah42 Can you take a look this please? It is holding up #192 and also #173. If you want to pass it off, please re-assign it and tell one of us how to do it.

**Comment by jarrah42** [comment]
https://projects.eclipse.org/projects/technology.ice/downloads

There is no master repo yet. The build is running now.

**Comment by jayjaybillings** [comment]
I just pointed it to next while the master build runs. As soon as it is over I will direct it back to master.

**Comment by jarrah42** [comment]
Can switch back to master now.

**Comment by jayjaybillings** [comment]
Done.
