### ISSUE TITLE
Build error, "Cannot resolve project dependencies"

### ISSUE THREAD

**Issue by kburova** [eclipse/ice#178]
I installed new ice, from **http://download.eclipse.org/ice/builds/next/** , cloned from github(next branch) and imported all the projects, i ran EAVP.launch, and got an error in the end of build:

-----------------------------------
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.ice.repository raw:2.1.8.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):2.1.8-SNAPSHOT
[ERROR]   Missing requirement: org.eclipse.ice.repository raw:2.1.8.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):2.1.8-SNAPSHOT requires 'org.eclipse.eavp.feature.feature.group [2.1.8.20160208]' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.ice:org.eclipse.ice.repository:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.repository/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
-------------------------------------

**Comment by kburova** [comment]
moved to EAVP issues list

**Comment by SmithRWORNL** [comment]
This is a known issue resolved in EAVP. However, ICE has stale versions of the EAVP packages in its repo. This should be resolved by having ICE pull EAVP from its p2 site, once that site is up.

**Comment by SmithRWORNL** [comment]
The changes above have been merged into next, per Issue #179 .
