### ISSUE TITLE
Client Thread creation refactor

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#180]
Currently, the Client's processItem function is creating and running a thread while having no way to synchronize with it. This is causing build failures in ClientTester (part of Issue #176 ). Alex and I discussed the problem, and propose that Client be refactored to take a thread creation factory. In real cases, this new factory class will function identically to Client's current code, but it will allow us to inject a fake thread factory which does not actually launch any new threads for use with test classes.

Since this plan would modify a core part of ICE's API, we thought it would be best to open an issue for discussion on how to deal with this test failure.

**Comment by jayjaybillings** [comment]
Anytime you run into a bug with a line like "Since this plan would modify a core part of ICE's API, we thought it would be best to open an issue for discussion on how to deal with this test failure," just go ahead and assign it to me. I know that's what you are waiting for. ;-)
