### ISSUE TITLE
VisIt tutorial should give sample paths

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#182]
The VisIt tutorial says:

Path: Enter the full path to the directory containing the VisIt executable,
not the executable itself. The VisIt executable is named visit on Linux and Mac
OS X. On Windows, VisIt.exe is the appropriate file.

It also shows a picture with a collapsed table.

Those things combined make for nearly useless documentation and I just received a bug report from a user who couldn't get VisIt working because the documentation did not share the proper Mac location.

Please provide concrete path examples such as:

"If your username if 'fluffy' and VisIt is in your home directory on a Mac, then the path is:

<whatever the path should be>

On Linux it would be:

/home/fluffy/programs/visit2_9_2.linux-x86_64/bin

and on Windows it would be:

<whatever it should be>"

**Comment by SmithRWORNL** [comment]
The wiki pages Visualizing Output in ICE and ICE Embedded Visualizations have been updated to include example paths for the three operating systems, as well as current information about which versions of VisIt are compatible with ICE.

The visualization tutorial has been similarly update by commit 5d9cf6d32f05061e96ffebe2e58c7ca81a742058.
