### ISSUE TITLE
Build Error on Project Generation

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#186]
Generating a new Item project starts off with a build error due to the fact that org.eclipse.core.runtime is not in the required bundles list.

**Comment by amccaskey** [comment]
This happened on my Mac Pro and not my laptop. Robert also said he didn't see it on his Windows.

**Comment by arbennett** [comment]
`org.eclipse.runtime` is in imported packages already.  Adding required bundles automatically would require more work, and we should be able to do this via the lighter weight mehod of package imports.  Do you know which subpackages would be needed to import to solve this issue?

**Comment by jayjaybillings** [comment]
I agree with Andrew that we need to favor Import Package over Require Bundle. Aside from this being written in multiple sources as a best practice, I think I might also have it written in our Dev Guidelines.

FYI - I didn't get any problems with org.eclipse.runtime. The actual problems I encountered were that org.eclipse.ice.io.serializable was not on the import package list.

We should just all try to run through this today.

**Comment by SmithRWORNL** [comment]
I tried this on all my machines. There were no problems with package imports for Windows 7, Mac OS X Mavericks, and Fedora 22. Opening the wizard crashed ICE on CentOS, because of #184 , so I don't have any results for it.

**Comment by arbennett** [comment]
Thanks @jayjaybillings and @SmithRWORNL.  I'm not seeing any errors on generation, and I do have `org.eclipse.ice.io.serializable` in the imported packages.  I've been using the `unstable-nightly` build.
