### ISSUE TITLE
Mac OS X Secure Storage Keystore Remote Launch Error

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#187]
When performing a remote job launch with ICE on a Mac, if the General > Security > Secure Storage > OS X Key Store Integration is checked ( which it unfortunately is by default ), then the Remote Services stuff cannot create a remote connection. 

Unchecking this preference fixes it. Maybe there is some way we can turn it off programmatically before remote job launches?

**Comment by amccaskey** [comment]
Removing org.eclipse.equinox.security.macosx from the run configuration bypasses this issue.

**Comment by jarrah42** [comment]
What happens when you try to create a remote connection? I don't think we want to remove this plugin as it may break other plugins that use secure storage.
