### ISSUE TITLE
JobLauncherForm Needs to Provide IProject instance to create File Entries

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#188]
If we pass the Item's project space to the JobLauncherForm then it could construct its FileEntries with the project space to enable auto-updating of its list of allowed values.

**Comment by jayjaybillings** [comment]
We can't do it that way. Data structures shouldn't know about org.eclipse.core.resources. The proper way to do this it to define some sort of updater interface that providers the entry with updates when it changes. Then the JobLauncher could realize that interface without polluting the JobLauncherForm.
