### ISSUE TITLE
Build EAVP feature

### ISSUE THREAD

**Issue by kburova** [eclipse/ice#191]
I downloaded latest unstable-nightly version of Ice and i don't have build EAVP feature under Developer menu. Alex and Robert said it should be in there.

**Comment by SmithRWORNL** [comment]
It shows up for me on Windows, so this may be OS specific.

**Comment by kburova** [comment]
For more information, I have Mavericks OS on my laptop. I'll try to test it on my home PC with Yosemite.

**Comment by SmithRWORNL** [comment]
If I remember correctly, this was an issue with having a less-than-current ICE install. It has been working for me on all my machines.
