### ISSUE TITLE
Need to mirror ICE at eclipseice.ornl.gov

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#192]
We need to mirror the ICE builds from the Foundation at eclipseice.ornl.gov. @amccaskey should be able to configure a nightly pull to do this.

**Comment by arbennett** [comment]
@amccaskey could you let me know when you fix this so I can get started on #173?

**Comment by amccaskey** [comment]
Fixed this with a script that nightly pulls down the builds at eclipse and copies them to eclipseice server.
