### ISSUE TITLE
ICE download page serving wrong version

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#194]
Today I downloaded ICE binaries from download.eclipse.org/ice/builds/next for both Mac and Windows, and I've noticed several regressions from ICE both as launched from a run configuration and from previous binaries downloaded from the same page on 4/18. This can be seen from the Developer Menu missing EAVP under Framework and a compilation error from org.bouncycastle.openssl not being in the default target platform, among others. I think these might be copies of binaries from ICE master or an earlier version of next.

**Comment by jayjaybillings** [comment]
Alex will fix this when he gets back.

**Comment by jayjaybillings** [comment]
What's the status on this?

**Comment by SmithRWORNL** [comment]
Just downloaded a Windows version from the official download page and tested it. It's able to save the Mesh Editor, meaning it must be a recent build, so this looks solved.
