### ISSUE TITLE
PlantComponentTester.java – references the “b******d Son of Eddard Stark".

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#196]
This needs to be fixed before our IC can pass review. I'll clean it up in a branch and push it to next.

Left by @jdeyton or @awoj!!!!!

Submitted by Sharon Corbett via email.

**Comment by jdeyton** [comment]
You can trace it back to the original source at the sourceforge site (It was not me... You can see the initial contribution at https://sourceforge.net/p/niceproject/code/3704/tree/trunk/tests/gov.ornl.nice.reactor.plant.test/src/gov/ornl/nice/reactor/plant/test/PlantComponentTester.java).

Although I do take full responsibility for starting to add GoT references to the test code. :)

**Comment by jayjaybillings** [comment]
The history on Sourceforge says it was @awoj! Mystery solved!
