### ISSUE TITLE
ICE downloads page no longer shows "Show Directory Contents"

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#199]
Our eclipse.org downloads page no longer shows the "Show Directory Contents" link since it is now using the mirror site. We need to reorganize our downloads so that the .zip files are at the top and the p2 site is in its own directory. It should be similar to:

http://eclipseice.ornl.gov/downloads/ice/unstable-nightly/latest/

This is critical. Right now none of our users can download ICE from the webpage!

**Comment by jarrah42** [comment]
This is already fixed, but is waiting for a successful build of ICE.

**Comment by jayjaybillings** [comment]
Do we have documentation on how the move to the ICE downloads directory is configured? We need to have more than one person (you) that knows how to do this.

**Comment by jarrah42** [comment]
In the org.eclipse.ice.repository/pom.xml? That's where everything relating to the repository happens.

**Comment by jayjaybillings** [comment]
Right, but I don't see something that says "This commands instructs the build to moves the files from the build directory to the download directory."

**Comment by jayjaybillings** [comment]
Oh, wait. Sorry! I was looking at the parent. I see it in the repository pom now.

**Comment by jarrah42** [comment]
I can add some more comments if that would make things clearer.

**Comment by jayjaybillings** [comment]
That wouldn't hurt, but I also added #200 to address the larger build documentation issues.

**Comment by jayjaybillings** [comment]
Confirmed that this is now fixed. Closing. Thanks!
