### ISSUE TITLE
Building master branch Failure

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#204]
I just tried to build master and got the following failure: 

ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.swtbot.eclipse.feature.group 2.3.0.201506081302
[ERROR]   Software being installed: org.eclipse.swtbot.eclipse.feature.group 2.4.0.201604200752
[ERROR]   Only one of the following can be installed at once: [org.eclipse.swtbot.eclipse.feature.jar 2.4.0.201604200752, org.eclipse.swtbot.eclipse.feature.jar 2.3.0.201506081302]
[ERROR]   Cannot satisfy dependency: org.eclipse.swtbot.eclipse.feature.group 2.3.0.201506081302 depends on: org.eclipse.swtbot.eclipse.feature.jar [2.3.0.201506081302]
[ERROR]   Cannot satisfy dependency: org.eclipse.swtbot.eclipse.feature.group 2.4.0.201604200752 depends on: org.eclipse.swtbot.eclipse.feature.jar [2.4.0.201604200752]

This happens after it tries to resolve EAVP-next - which presumably has updated its swtbot plugins?

**Comment by amccaskey** [comment]
Should we not have a master build of EAVP that ICE master can use?

**Comment by jayjaybillings** [comment]
Yes we should.

**Comment by jayjaybillings** [comment]
Actually, that gets a little complicated because then we end up needing to edit the target every time we merge. Probably best to leave it and just merge next into master.
