### ISSUE TITLE
ICE build cannot download required plugins

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#205]
The ICE build is currently unable to download all of its required maven plugins. Current builds are working only because of pre-downloaded plugins from previous working builds in our .m2 folders. In order to reproduce the bug, delete your computer's .m2 repository (be sure to back it up first), then clone a new version of ICE. 

I have a partial fix that addresses the problem of the tycho-maven-plugin no longer being available from the Eclipse CBI repository. However, it required me changing to the Tycho 0.26.0-SNAPSHOT build because I couldn't find a stable repo for 0.24.0 and the 0.24.0-SNAPSHOT is giving me an error when I try to use it. You can see it on the Robert/Build-Fix branch. If you get build errors related to the maven-plugin-api, try to clean the project and restart ICE. I'm still getting errors for other plug-ins, which I'm working on. 

@jayjaybillings I'm assigning this to you just to ask about the feasibility of changing our Tycho version, or if I just need to find a working repo for the 0.24.0 version, as I still intend to keep working on this myself unless I hear otherwise.

**Comment by jayjaybillings** [comment]
Didn't @jarrah42 fix this yesterday?

**Comment by SmithRWORNL** [comment]
The last commit I see for next was from a week ago. Was it in a branch?

**Comment by jayjaybillings** [comment]
Oh, it was you in your branch. Go ahead and push your fix. Let's see what happens!

**Comment by SmithRWORNL** [comment]
My fix wasn't working for me yesterday, and running it now it seems to be freezing the build. Let me investigate this a bit more, it may be something as simple as having needed to reboot my computer after deleting my .m2 directroy.

**Comment by SmithRWORNL** [comment]
My fix is working on my Windows (the build was just taking longer than normal) but not on my Mac laptop that I haven't done as much with. I'll go ahead and commit my change to next and see if anything breaks, though it may require a reboot and/or to run maven clean install -U once to force plugin updates.

**Comment by jayjaybillings** [comment]
Trying switching the version to 0.25 instead of 0.26-SNAPSHOT. The latest version of Tycho rarely works.

**Comment by SmithRWORNL** [comment]
I found a working repo with 0.24.0, so we should be fine keeping our current version. I've put the change in next with commit a73f141a1b8bed759c91083883cb42782ebc4054 and we'll see if it builds.

**Comment by jayjaybillings** [comment]
I don't like using mvnrepository.com. Why do we need to use it? Isn't Tycho 0.24 in Maven Central?

**Comment by jayjaybillings** [comment]
And for that matter, just change the version if you need to as long as it works. Changing the version isn't something that only I can do...

**Comment by SmithRWORNL** [comment]
I've switched it to the maven.org repo with commit 641fa9c4a558baa18ca9e56ceedf2190ec0d565c. 

The version number per se wasn't the issue, it's just that the Eclipse Tycho repo skipped from version 0.23.0 to 0.25.0 for some reason, so I couldn't use our original version with it. 0.24.0 is in the official Maven repo and works fine, so there's no reason to change it.

**Comment by SmithRWORNL** [comment]
The build is working again and I've corrected the same problem for EAVP's build.
