### ISSUE TITLE
Create a template RCP app that can be easily customized as a stand-alone frontend

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#207]
It would be nice to have an RCP app template that user's can add their item plugins to in order to create a standalone frontend for a specific code. The RCP app would just provide the ICE perspective will all the other menus and toolbars removed.

**Comment by jayjaybillings** [comment]
We used to have this, but I wanted to have a fully dev-enabled version of ICE. Lately we have run into more users requesting that we drop all the developer stuff and get back to basics.

We also need to do this for better web support with RAP.
