### ISSUE TITLE
Need more mature control scheme in the Geometry Editor

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#216]
The Geometry Editor has very little in the way of useful controls. The basic controls should be similar to something like Blender, http://www.katsbits.com/tutorials/blender/basic-keyboard-mouse-movement-control.php.

**Comment by SmithRWORNL** [comment]
Blender mouse controls were added to EAVP with commit 4d0e95a2d8cfb33ac9e8402c44cfe626d9eaec35.

I'll leave the bug open to give you a chance to ask for any additional camera features you may want (such as a way to reset, pitch, or yaw the camera.)

**Comment by jayjaybillings** [comment]
Which Blender mouse controls were added? Blender has about a million different controls, so please point to some documentation on what you added specifically, preferably on the wiki or in one of the user tutorials.

**Comment by SmithRWORNL** [comment]
@jayjaybillings 
The ones on the page you linked in the bug report. Specifically, holding down shift while dragging will move the camera about the 3D space and holding control while dragging up or down was added as a second way to zoom. 

Updating the documentation is on my todo list for writing day.
