### ISSUE TITLE
Nek5000 Model Builder isn't working

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#219]
I attempted to follow the tutorial at [the wiki](https://wiki.eclipse.org/Using_Nek5000_with_ICE). However, even after placing the conj_ht.rea file in ICEFiles/default/Nek500_Model_Builder and restarting ICE, new Nek5000 Model Builder Items are just a mostly empty form containing a drop down box with the text "No examples available." According to the tutorial, it should have populated the form to allow editing the file. Attempting to import the .rea file as an ICE Item produced the same result. Either the documentation needs to be updated or the Nek5000 Model Builder is broken.

**Comment by SmithRWORNL** [comment]
The documentation was incorrect, and I've updated our Nek5000 tutorial accordingly. As of commit 62dd75b31aed094cad15e722be81c0ba47680a7f the Nek5000 Model Builder is now working again.

**Comment by jayjaybillings** [comment]
I reopened this because your fix broke the build, so it isn't working.

**Comment by SmithRWORNL** [comment]
Build error fixed by commit ba1b0c19a98ddd9fbed2c331305afc1897968ff0
