### ISSUE TITLE
jay/january/org.eclipse.january.form.feature is missing about.html

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#223]
The org.eclipse.january.form.feature bundle is missing the about.html file in the jay/january branch.

**Comment by SmithRWORNL** [comment]
I notice that the org.eclipse.ice.feature bundle also lacks an about.html file. Does it need one too?

**Comment by jayjaybillings** [comment]
Yes. Thanks!

All bundles need these files.

**Comment by SmithRWORNL** [comment]
Fixed by commit 2285e5e86a07e468783e3d8c0239e3f370ff4b43
