### ISSUE TITLE
javax.ws.rs version

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#225]
The parent pom contains a filter to restrict the version of java.ws.rs:

&lt;filter&gt;
&nbsp;&nbsp;&lt;type&gt;eclipse-plugin</type&gt;
&nbsp;&nbsp;&lt;id&gt;javax.ws.rs&lt;/id&gt;
&nbsp;&nbsp;&lt;restrictTo&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;version&gt;1.1.1.v20130318-1750&lt;/version&gt;
&nbsp;&nbsp;&lt;/restrictTo&gt;
&lt;/filter&gt;

Does anyone know the reason for this? I've tried removing this for the Neon build and it seems to work ok (all the tests pass), so I'm wondering what might break if it is removed.

**Comment by jayjaybillings** [comment]
I believe that is for some stuff that @amccaskey is doing. It used to be for some other stuff that we moved into the target.

**Comment by jarrah42** [comment]
I'm going to take it out for now as it is no longer available in the latest Orbit build.

**Comment by amccaskey** [comment]
So this is an issue for us in that we use Jersey 1.17 which requires javax.ws.rs 1.1.1. I ran into this issue when integrating the Docker stuff awhile back - check out the discussion in 

https://github.com/eclipse/ice/issues/156 

The DockerClient required Jersey 2.0 - which brought in javax.ws.rs 2+ which in turn broke our Real-Time Updating stuff. 

Sounds like we want to remove the docker support anyway. I'm not sure what removing the 1.1.1 restriction on javax.ws.rs will do for our real-time updating. It would be good to upgrade or Jersey to 2+

**Comment by jayjaybillings** [comment]
Well, we don't want to remove Docker support in general, we just don't want it to be a requirement for the tutorial. In fact, we will need it for the CADES work.

**Comment by jayjaybillings** [comment]
And RENT work.

**Comment by jayjaybillings** [comment]
RNET, not RENT.
