### ISSUE TITLE
Python Install script not working

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#226]
I've tried running the Install_ICE.py script on two different Linux machines. In both cases, I got the following output 

Preparing to install ICE...

Downloading and installing:
  ICE
  VisIt
  HDFJava
Downloading ICE:
Traceback (most recent call last):
  File "Install_ICE.py", line 473, in <module>
    main()
  File "Install_ICE.py", line 466, in main
    pkg_files = download_packages(opts, os_type, arch_type)
  File "Install_ICE.py", line 175, in download_packages
    u = urllib2.urlopen(url)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by arbennett** [comment]
Where did you download the installer from?  It was updated so that it shouldn't download HDFJava anymore, so I'm thinking you've got an old version pointing to the SourceForge hosted builds.

**Comment by amccaskey** [comment]
Looks like its updated in next but not master yet. Master still references the incorrect package names ice.product*

**Comment by SmithRWORNL** [comment]
@arbennett We have links to two different scripts on our Getting ICE page, one that goes to eclipseice.ornl.gov, and one that goes to github. I tried the ornl.gov version, so I'll try the one from the Github link next and update the wiki if it works.

**Comment by arbennett** [comment]
I just looked through the one on eclipseice.ornl.gov and it is an old version.  @amccaskey are you the one to ask to update it?

**Comment by amccaskey** [comment]
Yea I can do that.

**Comment by SmithRWORNL** [comment]
The version on Github worked for me. I did get the following error on my machine before I updated my Python version:

File "Install_ICE.py", line 186
    info = {k.lower():v for k,v in dict{u.info()).items()}
                                     ^
SyntaxError: invalid syntax

So it may be worthwhile to investigate and document what the minimum required version of Python to run the script is.

**Comment by amccaskey** [comment]
I just updated the script on eclipseice. 

@SmithRWORNL what machine was that on and what version of python?

**Comment by SmithRWORNL** [comment]
Stampede and it failed with Python 2.6.6. Updating to Python 2.7.9 resolved the issue.

**Comment by arbennett** [comment]
Ooh, that's supposed to be caught [here](https://github.com/eclipse/ice/blob/next/org.eclipse.ice.installer/Install_ICE.py#L33-L44), but it's not catching.  I'll play around with it and try to get it to work.  The installer is only compatible with Python 2.7+.

**Comment by SmithRWORNL** [comment]
I've run into another small issue. The script downloads VisIt 2.10.1, but the latest version of VisIt supported by EAVP is 2.9.2 (see eclipse/eavp#24)

**Comment by arbennett** [comment]
@amccaskey this sounds like another one for you.  eclipseice.ornl.gov only has VisIt 2.10 on it.  I have the backup download of VisIt set to be version 2.9.1 in case eclipseice.ornl.gov is down.

**Comment by amccaskey** [comment]
Working on it now.

**Comment by arbennett** [comment]
@SmithRWORNL the 2.6 error message should now work as of d0a3cbb95721808de4c73cd8e4d3ef8879d1f8ca .  The issue was that dict comprehensions were not introduced until python2.7.  Note that the installer still does not support python2.6 due to standard library differences between versions.  Now you ought to get a nice error message telling you to upgrade to python2.7 or higher at least.

**Comment by amccaskey** [comment]
@SmithRWORNL I've updated the visit directory on eclipseice with visit 2.9.2

**Comment by amccaskey** [comment]
@arbennett you should have to update the script again to account for the new version numbers.

**Comment by arbennett** [comment]
Updated in 850a3a58ab74ee243891fb00aad8b6bedff900ee
