### ISSUE TITLE
ICE version

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#231]
Should we increment the ICE version for Neon?

**Comment by jayjaybillings** [comment]
Sure. Once next works, increment the version number to 2.1.9 and push it to master.


Our October Eclipse release will be 2.2.


Jay


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by jarrah42** [comment]
Any reason not to make next 2.2 now?

**Comment by jayjaybillings** [comment]
Yes, as I explained previously (the last time you asked that! ;-)), our versioning for the current 2.x line of ICE is controlled by two things:
1.) The commitments we've made to DOE in the past about version numbers and releases, which means we have to release greater than 2.1.
2.) What I perceive as our progress towards a release with the Foundation and exit from incubation, which means that once we have everything we need for a full minor version increment, we will do a 2.2 release.

In the present context, that means that all we are fixing for the XSEDE releases are bugs and that we are not adding any new, major functionality or IP clearance. Our next scheduled release is in October as part of the Fall Release for the SWG, which will mark our exit from incubation and full IP clearance, so we will go to 2.2. The following release - hopefully as part of the Oxygen sim rel - will either be 2.3 or 3.0, depending on my progress towards the Mark III and our feelings on preserving the 2.x line.

**Comment by jarrah42** [comment]
Are you planning to make a 2.1 branch? That would seem to be the only reason not to set the version to 2.2 and just consider it a pre-release version until the official release. It just seems a waste of time to change everything to 2.1.9 and then later to 2.2 when we're not having an actual release in the mean time.

**Comment by jayjaybillings** [comment]
We are doing a 2.1.9 release, but it will be through ORNL at eclipseice.ornl.gov, not the Foundation. We put all of our releases there, (although 2.1.7 vanished...). Note 2.1.8 was in November and the reflectivity release was in May.

I don't think it is a waste of time for the reasons I listed above.

It probably makes sense to do a 2.1.9 branch, yes, but as I said, there are the other reasons I mentioned too. So, after we do 2.1.9 and put it in a branch, I don't care if we increment to 2.2 and then look at it as a pre-release. In fact, it would probably be good for us to push a few 2.2 RCs to the Foundation servers.

**Comment by jarrah42** [comment]
No further action required.
