### ISSUE TITLE
Implement Developer Menu Action for Launching Instance of ICE with new plugins

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#232]
It would be good for our tutorials if there was a one-click way for launching a new instance of ICE with new Item plugins added to the launch configuration.

**Comment by jarrah42** [comment]
It would be even better if it would generate an RCP app with the new plugins!

**Comment by amccaskey** [comment]
addressed in eb871f4a511325b2a96aada588592c801bc3ec16
