### ISSUE TITLE
Default workspace location

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#237]
I'm confused about the workspace location settings. The product configuration sets osgi.instance.area.default=@user.home/Documents/workspace, but the launch arguments specify "-data @noDefault". The upshot is that (for OS X anyway), the workspace location ends up being inside the application bundle. I tried removing the "-data" argument and it works properly. I'm assuming that the "-data" option was so that the user would be forced to choose a new workspace when launching an instance. Is that correct?

**Comment by jayjaybillings** [comment]
Yes. In the past we have needed the -data argument to force the new workspace box to pop up. If you are going to remove it, be sure to check that it works
1.) with a clean build of ICE that hasn't been run before
2.) with all OSes from which you remove that argument in the launch configuration.

I'm not sure why the product configuration is setting the instance area default argument. I have previously removed all of those calls, so please feel free to remove that too.

**Comment by jarrah42** [comment]
addressed in ece712

**Comment by jarrah42** [comment]
Closing as fixed.
