### ISSUE TITLE
Remove bundles to avoid bloat

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#238]
The ICE app weighs in at almost 900MB (OS X). We should remove some bundles that are unlikely to be used to reduce the size. Jay mentioned EMF, but other suggestions appreciated.

**Comment by jarrah42** [comment]
I've removed about 200MB of content, however we should really have a list of the functionality (and consequently the features) that are included. I'll open a separate issue on this.

**Comment by jayjaybillings** [comment]
EMF is the biggest by far.

My philosophy on this has been to cram everything that scientific software developers would want into our build, but lately, as you say, ICE's size has become a serious issue. I think what would make the most sense - at least to me - is to put a short cut under the developer menu that will automatically try to install the following packages
* the EMF tools (~500MB)
* the web tools (~200MB)
* select parts of PTP (~50MB & up to you)

Let me know what you think about this. @amccaskey too. We can create a separate ticket for updating the dev menu if we go this route.

**Comment by jarrah42** [comment]
It's a good idea to provide an easy way to add features. I'm concerned that the developer menu will become a bit of a pain to maintain, since we'll have to continually revise and update the content. Something like the marketplace would be a better long term solution. I think it would be worth looking at providing a simplified and/or customized version that references our content.

**Comment by jayjaybillings** [comment]
Yes, you are absolutely right. A separate/the marketplace makes perfect sense for existing Eclipse content.

What I haven't figured out yet is whether or not we can use the marketplace to pull in project source code like we do in the developer menu. I would love to have a little marketplace client in place of the lists we are making in the dev menu.
