### ISSUE TITLE
Initial perspective

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#239]
Currently, when opening a new workspace, ICE starts by displaying the Resource perspective. I'm not sure this is really ideal. It seems like there are actually two perspectives that matter. The first is the PDE perspective, which is generally where you want to be when developing ICE, Items, etc. The other perspective is the ICE perspective, which is where you want to be when running an instance of ICE with the application customizations.

I would suggest we modify the downloaded ICE package so that it starts in the PDE perspective by default. This is probably the most common place developers are going to want to be when starting to develop on ICE. We then change the RCP app version of ICE so that it starts using the ICE perspective. This would be the version that is launched as an ICE instance, or when ICE is built as an RCP application.

**Comment by jayjaybillings** [comment]
Yes. Good point. 

I've been thinking for the past couple of months that we might want to consider creating two separate ICE products, kind of like an "ICE Runtime Environment" and an "ICE Software Development Kit," where the former is just ICE+RCP and the latter is ICE with developer tools, which would now be configured as I mention in #238 with the developer menu doing the bulk of the work.

My thoughts have been going this way as I consider both the pressing need to get ICE on the web and the Mark III.

**Comment by jarrah42** [comment]
We could do this by creating an ice.sdk.product. That way we can customize the content of the SDK vs. the runtime version.

**Comment by jayjaybillings** [comment]
Yes, that is what I meant. The more I think about it the more I think it might be ideal.

**Comment by jarrah42** [comment]
I've split the product into two: sdk and runtime. The sdk is the one you download from eclipse.org and this will start up in the PDE perspective. The runtime one will launch as an instance and can also be used when customizing an application RCP (e.g. from a new Developer menu item). This will start up in the ICE perspective.

I've changed the name of the sdk executable to ICE_SDK, however we should probably also have a different icon at some point.

**Comment by jayjaybillings** [comment]
Okay. What branch is this in?

**Comment by jarrah42** [comment]
next

**Comment by jarrah42** [comment]
Completed.
