### ISSUE TITLE
Add developer menu to import from local git repo

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#241]
I know Alex has already done this, but I want to track it.

**Comment by jarrah42** [comment]
Can we change the name to "Import Local Repository"? 

Also, do we need "ICE" in all the menu items, since they are all under the "ICE" submenu?

**Comment by jarrah42** [comment]
I'm also still seeing the lifecycle errors. Not sure if you fixed that already.

**Comment by jayjaybillings** [comment]
Agreed that it is a bit weird to include "ICE" everywhere in the submenu.

**Comment by jarrah42** [comment]
Opened #242

**Comment by jarrah42** [comment]
Starting from a brand new workspace, I'm still seeing lifecycle errors. Looks like this may be specific to Mac/Windows?

**Comment by SmithRWORNL** [comment]
I think the pom lifecycle management errors might not be related to the new import local repo action. I just downloaded the latest nightly, and I'm getting the errors after using the standard Clone Ice command in the Developer menu.

**Comment by amccaskey** [comment]
this was implemented in b642957173432fe16a59691fb41cb4170187db3f
