### ISSUE TITLE
Update CoreTester.checkRealTimeUpdates to do an HTTP post

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#250]
Can/should we update this line of code 

https://github.com/eclipse/ice/blob/master/org.eclipse.ice.core.test/src/org/eclipse/ice/core/test/CoreTester.java#L574

to do an actual HTTP Post instead of just calling the method on the iCECore reference? Seems like this would catch the problems discussed in #156 #249 #225

**Comment by jayjaybillings** [comment]
It would probably be better to make it look like the TASQC tests and put it and other tests in the core.jaxrs.test bundle, which would then need to be added to the build.
