### ISSUE TITLE
ICEResourcePage fails if browser is not available

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#254]
The ICEResourcePage will fail to display a resource without an error if the resource is neither a visualization nor a text file and ICE is being run on an operating system for which the internal web has not been set. The page should display an error message telling the user to set up their web browser and attempt to open files in a text editor as a fallback if no browser is available.

**Comment by jayjaybillings** [comment]
I think the problem is that it tries to load an SWT Browser Widget, but instead it should get the Browser from the Eclipse Platform, which will switch between an internal and external browser. This bug came up a few years ago and I just ignored it because the person got the same fix as Ram.
