### ISSUE TITLE
EASE Jython engine CQ?

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#258]
Do we need a CQ for the EASE Jython Engine? What is the status of its IP?

**Comment by jarrah42** [comment]
Jython has been approved as works-with (CQ 9763). We probably need to move this to the dev menu.

**Comment by jayjaybillings** [comment]
Yes. We can't have it in our target it if it is only Works-With.

Please catch up with @amccaskey to figure out how to get this in the Developer menu.

**Comment by jayjaybillings** [comment]
Closing this bug since its purpose was only to document the status of the CQ. Opened #259 for the work.
