### ISSUE TITLE
Update Javadoc

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#270]
Our Javadoc needs to be regenerated for the release, posted, and linked on the Wiki. The current links are broken and/or out of date.

**Comment by SmithRWORNL** [comment]
I've generated the Javadoc for ICE and EAVP. The old version was hosted on sourceforge, but I'm not sure where you'd prefer we host the new Javadoc.

**Comment by jayjaybillings** [comment]
Ideally we would host them at eclipse.org, but the web team isn't fixing my credentials. How big are they? Could we cram them in a the repos? If not, we will upload them to eclipseice.ornl.gov/downloads/ice and point to them.


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by SmithRWORNL** [comment]
They're 30MB and 45MB. Is that small enough for them to go in the repos? If not, I don't think I have access to upload on eclipseice.ornl.gov

**Comment by jayjaybillings** [comment]
That's too big. We'll need to upload them. I'll email you.


Jay


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by amccaskey** [comment]
I have posted the ICE javadocs at http://eclipseice.ornl.gov/downloads/ice/javadoc.

**Comment by SmithRWORNL** [comment]
Updated the Eclipse wiki to point to the new javadoc site.
