### ISSUE TITLE
eclipseice.ornl.gov is no longer fetching executables

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#273]
Since ICE was changed to version number 0.1.1, eclipseice.ornl.gov has only been mirroring the p2 repository from eclipse.org, not the products.

**Comment by jayjaybillings** [comment]
@amccaskey Can you fix this please? It would be good to have this fixed early in the week because the release is on Friday.

**Comment by amccaskey** [comment]
I've update the versions in the download URLs in the mirror script on our dev server. Running now, downloads taking forever, but I think it should be good to go.

**Comment by jayjaybillings** [comment]
This looks like it is working. As for the slow downloads, you should pull them from a mirror site instead of from the Eclipse servers directly.
