### ISSUE TITLE
Saved JobProfileEditor fails to load

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#278]
Wei (Mark) Jin reported the following:

Here I came across a new problem on Job Profile Editor :

I created a new Job Profile using dir.exe on Windows 7 X64, then restarted ICE, click new Item, found new job profile I created, double click and a error dialog came out as "java.lang.ClassCastException: com.sun.org.apache.xerces.internal.dom.ElementNSImpl cannot be cast to org.eclipse.ice.datastructures.entry.IEntry".

Did I miss something ? Need your help, Sir : )

Many thanks again~~

Mark

below is the detail.

> java.lang.ClassCastException: com.sun.org.apache.xerces.internal.dom.ElementNSImpl cannot be cast to org.eclipse.ice.datastructures.entry.IEntry
> at org.eclipse.ice.datastructures.form.DataComponent.copy(DataComponent.java:355)
> at org.eclipse.ice.datastructures.form.DataComponent.clone(DataComponent.java:378)
> at org.eclipse.ice.datastructures.form.Form.copy(Form.java:373)
> at org.eclipse.ice.item.Item.copy(Item.java:1283)
> at org.eclipse.ice.item.jobLauncher.JobLauncher.copy(JobLauncher.java:1806)
> at org.eclipse.ice.item.jobLauncher.JobLauncher.clone(JobLauncher.java:1840)
> at org.eclipse.ice.item.SerializedItemBuilder.build(SerializedItemBuilder.java:238)
> at org.eclipse.ice.core.internal.itemmanager.ItemManager.createItem(ItemManager.java:187)
> at org.eclipse.ice.core.internal.Core.createItem(Core.java:408)
> at org.eclipse.ice.core.internal.Core.createItem(Core.java:389)
> at org.eclipse.ice.client.internal.Client.createItem(Client.java:314)
> at org.eclipse.ice.client.common.wizards.NewItemWizard.performFinish(NewItemWizard.java:132)
> at org.eclipse.ice.client.common.wizards.NewItemWizardPage$4.doubleClick(NewItemWizardPage.java:245)
> at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:833)
> at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
> at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
> at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
> at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:830)
> at org.eclipse.jface.viewers.StructuredViewer.handleDoubleSelect(StructuredViewer.java:1151)
> at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1264)
> at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:252)
> at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:249)
> at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:311)
> at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
> at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
> at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
> at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
> at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
> at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
> at org.eclipse.jface.window.Window.open(Window.java:794)
> at org.eclipse.ice.client.common.CreateItemHandler.execute(CreateItemHandler.java:49)
> at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
> at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
> at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
> at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
> at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
> at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
> at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
> at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
> at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
> at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
> at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
> at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
> at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
> at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
> at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
> at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
> at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
> at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
> at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
> at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
> at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
> at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
> at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
> at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
> at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
> at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
> at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
> at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
> at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
> at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by jayjaybillings** [comment]
It is worth noting that the JobProfileEditor has not seen a lot of love in the past few years, so likely this is simply a matter of properly updating it given the changes to the data structures and persistence engine. (Famous last words?)

**Comment by jayjaybillings** [comment]
This fix should go on the 2.2.1 branch and then be merged into next and master.

**Comment by jayjaybillings** [comment]
@SmithRWORNL or @amccaskey will you look into this please?

**Comment by SmithRWORNL** [comment]
@jayjaybillings Looking into it right now. It seems that the JobLauncherForm is getting populated with an invalid data component that's causing a class cast exception when it gets copied.

**Comment by jayjaybillings** [comment]
Oh, who would have written that code? #looksforascapegoat ;-)

**Comment by SmithRWORNL** [comment]
According to the documentation comments, someone by the name of Jay Jay Billings. #lookinamirror

**Comment by SmithRWORNL** [comment]
Fixed by commit af75fe8882994601f8d0729ed24dcf03cd428f87.

**Comment by jayjaybillings** [comment]
Fixed a bug with the SerializedItemBuilder where the
ICEJAXBClassProvider was not being used to get a full list of
unmarshalable classes.

**Comment by jayjaybillings** [comment]
@SmithRWORNL Did you respond back to the emails on the list to let Mark know to try this out?

**Comment by SmithRWORNL** [comment]
@jayjaybillings I just emailed him to let him know to try out the unstable nightly.
