### ISSUE TITLE
Some bundle poms at version 0.1.1-SNAPSHOT in master

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#280]
Some of the plugin pom files have their versions set to 0.1.1-SNAPSHOT. These should be 2.2.0-SNAPSHOT.

**Comment by SmithRWORNL** [comment]
Fixed in the 2.2.1 branch by commit 8224b13d7bec630d4ce594975237eab8d3c92525.

**Comment by jayjaybillings** [comment]
I'm reopening this. Has anyone checked with Ram to see if he still sees the issue on his machine?

**Comment by SmithRWORNL** [comment]
Ram replied and confirmed it was working for him as well.
