### ISSUE TITLE
[ice-dev] Usage of Core OSGI.launch 

### ISSUE THREAD

**Issue by palculois** [eclipse/ice#282]
Ram is attempting to figure out how to use the As->Core OSGi.launch file but he gets errors instead. 

>As part of work on launching the Core separately, I have noticed a Core OSGI.launch file under org.eclipse.ice.core folder. I was wondering if this was originally meant to launch a Core instance or test it out separately?
 
>1) When I right-click and try to Run As->Core OSGi.launch, it looks like it launches an OSGi container and I get some FrameworkEvent errors. Can anyone give some advice on how to use this file and/or correct the errors?
 
>I had tried this out with the latest 'next' branch and I have attached a screenshot which shows a part of the console output.
 
>2) I have now used OSGi Declarative Services (DS) to try and run Core as a Remote service. My changes are in https://github.com/knram06/ice/tree/remoteosgi3 . I have also enabled the auto-generation of OSGi metadata, based on http://www.vogella.com/tutorials/OSGiServices/article.html#declarativeservices_annotations for the relevant XML files.
 
>Would it be possible for anyone to evaluate the changes? I am still not seeing a listener at port 9278.

**Comment by jayjaybillings** [comment]
Fixed in 7f3c549eb2f0c2691cf6481de34cd2a8a1f9df1d
