### ISSUE TITLE
Re-add hosts table file for JobLaunchers

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#290]
We need to have the ability to change the default hosts in a JobLauncher at deployment time in addition to build time and run time.

Once upon a time we had this ability, but I dumped it years back. The simplest way to do this is to provide a file that lists the extra hosts and to read that file on startup. In the past this depended on on a hardwired path in the workspace, but I will configure this so that the user can provide a path in the ICE INI file instead.

**Comment by ds-ga-1007** [comment]
Won't the job launcher be using the hosts provided by o.e.remote? It would be better to do this only in one place rather than two.

**Comment by jarrah42** [comment]
That was me btw.

**Comment by jayjaybillings** [comment]
Well, until this morning I was under the impression that the JobLauncher knew nothing about the IRemoteConnection interface, but I just noticed that it has creeped in. We could in principle just call

```java
remoteManager.getAllRemoteConnections().get(i).getName();
```

to get all the connection information, I think. 

I am reluctant to do it that way though because PTP is preventing me from running the o.e.i.item bundle in RAP or doing remote connections headlessly, both of which I need to be doing sooner rather than later. 

I suppose we could just do it this way for 2.2.1 and figure out a better way to do it later. (Probably through a PTPJobLauncher subclass provided as a service or something.)

**Comment by jarrah42** [comment]
There shouldn't be anything in the o.e.remote bundles that prevents this. You may have to remove the ptp bundles until I can fix the dependencies.

**Comment by jayjaybillings** [comment]
Greg Watson is going to take this.

**Comment by jayjaybillings** [comment]
Once you and @dalg24 (Damien) get a look at whether or not the preferences file switch works, then we can update the Launcher.
