### ISSUE TITLE
Reflectivity Models are improperly set up when opened from .xml files

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#291]
A Reflectivity Model can be persisted to .xml and reopened.  However, the NatTable in the model's page will  be empty and the different Components of the form will be listed on a separate page each once the .xml file is opened. This seems to be caused by the object getting an EclipseFormWidget instead of a ReflectivityEclipseFormWidget.

A workaround is to open the xml file, close the Model, then open it again in the Item Viewer, which will initialize the form correctly.

**Comment by jayjaybillings** [comment]
Grr. Okay.
