### ISSUE TITLE
Host table is requiring connection information to be reentered

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#295]
Entering an unrecognized connection name in the hosts table in an Item, then configuring the connection so that it fails, may result in the table forcing the user to re-input all the information for the connection every time the Item is processed, even after it has already been replaced by a valid connection in the table.

**Comment by SmithRWORNL** [comment]
User has confirmed that this was fixed by commit 8033cd128fc3effdeca4b66aed84b039aee34ee3

**Comment by jayjaybillings** [comment]
I added some comments to the 8033cd1 commit. Please look at them.

**Comment by SmithRWORNL** [comment]
Fixed commented out code issue with commit ec2e3d3640626d3cc9a6bcbf7b21f9c921ade403 and applied fix to 2.2.1 with commit 84ca59ee87938a62644fad330327d2452cfeec59

**Comment by jayjaybillings** [comment]
Thanks. You should ask @amccaskey to make sure this still works for his stuff.
