### ISSUE TITLE
The ICE version is not populated in the About ICE dialog. It only says Version: next.

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#297]
The ICE version is not populated in the About ICE dialog. It only says Version: next.
![image](https://cloud.githubusercontent.com/assets/4369008/20720275/8d3743dc-b62c-11e6-8068-7e849cae031b.png)

**Comment by jayjaybillings** [comment]
Good catch. @jarrah42 will you look at this with @klaskyhb please?

**Comment by jarrah42** [comment]
Set by the releaseName attribute in the parent pom.xml. Typically this would be changed to an actual release name when it is known, but should stay as is in the next branch.

**Comment by jayjaybillings** [comment]
Ah, I see. Okay, I'll close this since it isn't a bug.

Looking at this now I notice that @klaskyhb is using the XSEDE build. @klaskyhb you might want to update to 2.2 or the latest stable nightly.
