### ISSUE TITLE
ICE XSEDE Tutorial, section 1.2.2 provide the location and the name of the executable file referred.

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#298]
On ICE XSEDE Tutorial, section 1.2.2 it says: “To start ICE, double-click on the application executable to open up ICE.” However, no executable file name is mentioned. Documentation should provide the location and the name of the executable file that it is being referred.

**Comment by jayjaybillings** [comment]
@klaskyhb These files are in the doc/ folder of our directory. Would you be willing to try fixing this error on your own and issuing a pull request?  (See CONTRIBUTING.md for more info.)

**Comment by klaskyhb** [comment]
Yes, I will work in fixing this error on my own and issuing a pull request.

**Comment by SmithRWORNL** [comment]
Fixed by pull request #311
