### ISSUE TITLE
ICE XSEDE Tutorial, section 4.4.1 typo: duplicated word 'the'

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#299]
ICE XSEDE Tutorial, section 4.4.1 typo at:

“4.4.1 Opening a Plot Editor
To open a Plot Editor, a ﬁle that uses this editor must ﬁrst be placed in the Project Explorer. This view lists ﬁles imported into ICE. To access the Project Explorer, use **the the** menu bar at the top of the window and navigate to Window → Show View → Project Explorer.”

**Comment by jayjaybillings** [comment]
As I mentioned in #298 this would be a really good place for you to start making pull requests.

**Comment by klaskyhb** [comment]
Yes, I will work in fixing this error on my own and issuing a pull request.

**Comment by SmithRWORNL** [comment]
Fixed by pull request #311
