### ISSUE TITLE
Java was started but returned exit code = 13, error on Windows

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#300]
I saw the following error message after double clicking the ICE_SDK ice.sdk.product-win32.win32.x86_64 on Windows 10 after installation. I couldn't reproduce it when a first saw it two weeks ago. 

Somehow, I'm unable to run the ice.sdk.product-win32.win32.x86_64 again, I get the above error all the time. Surprisingly, the ice.sdk.product-win32.win32.x86 starts with no problem. Both, in a Windows 10, 64 bit computer. The work environment details are below.

![image](https://cloud.githubusercontent.com/assets/4369008/20759774/e824c5c0-b6eb-11e6-8267-44854c3acb34.png)

Work environment details:
![image](https://cloud.githubusercontent.com/assets/4369008/20759788/f998766c-b6eb-11e6-8a75-26aba3b5e232.png)

![image](https://cloud.githubusercontent.com/assets/4369008/20759794/fff3cdae-b6eb-11e6-8d38-200e17b108e7.png)

Java path:
C:\Program Files (x86)\Java\jre1.8.0_111\bin

**Comment by SmithRWORNL** [comment]
@klaskyhb Do you have multiple Java installations on this machine? Your java version is showing that it's a 32 bit version. Your java path may have been changed so that it's now defaulting to this 32 bit installation rather than the 64 bit version.

Try editing your ICE_SDK.ini file to include 

```
-vm
C:\Path\To\Your\64\bit\Java\Install\java.exe
```

right after the 

`--launcher.appendVmargs`

line

**Comment by T-e-j-k-u-m-a-r** [comment]
Facing the same issue, My system is 64 bit windows 10
But I need java 8 for appium (mobile automation project) 

I tried the above steps, But eclipse is not launching.. 
![eclipse-launching-error](https://user-images.githubusercontent.com/54025065/68373940-de3db000-0169-11ea-9802-385b46b92b29.PNG)

Please find the error screen shot attached for the same..
