### ISSUE TITLE
Fix malformed package names

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#302]
The org.eclipse.ice.core plugin contains the packages:

org.eclipse.ice.core.internal
org.eclipse.ice.core.internal.itemmanager

According to the [Naming Conventions](https://wiki.eclipse.org/Naming_Conventions#Java_Packages) these should be:

org.eclipse.ice.internal.core
org.eclipse.ice.internal.core.itemmanager

**Comment by jayjaybillings** [comment]
Thanks for catching this. This bundle is due for an overhaul in the next few months, so we can take care of it then.

**Comment by jayjaybillings** [comment]
Notice too that everyone one of our testing bundles is named incorrectly according to the naming conventions.
