### ISSUE TITLE
The URIs mentioned in wiki page 'Forking Eclipse ICE' need to be consistent...

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#307]
The URIs mentioned in wiki page 'Forking Eclipse ICE' need to be consistent.

See eclipse ice wiki page at http://wiki.eclipse.org/Forking_Eclipse_ICE. In the latter page I found two occurrences in which the URI is not consistent. 

1. In section 'Cloning the Fork Repository' where it says: '...but instead of https://**github.com**/eclipse/ice.git, use https://**github**/[your username]/ice.git as the URI.' Note that the first URI in the latter sentence is correct, however, the second URI only reads **github**, it should read **github.com**

2. On section 'Pulling from the Master Branch', where ti says: 'git remote add upstream https://github.com/**Eclipse**/ice' it should say: 'git remote add upstream https://github.com/**eclipse**/ice'. Note that there should not be a capital 'E' in the 'eclipse' word in the latter case.

Note that the next URI reference in the latter page, where it says: 'Once you are ready to submit the pull request, return to GitHub. From your repository page, http//github.com/[your username]/ice' is correct, as the ice.git extension is not required.

**Comment by jayjaybillings** [comment]
Thanks Hilda! Will you go ahead and edit those pages? You can log into the wiki with your eclipse.org account.


Jay


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by klaskyhb** [comment]
Fixed issue #307 as described above. Waiting for fix to be approved.
