### ISSUE TITLE
New remote connections are not saved on Windows

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#315]
The New Connection dialog (such as created from the MOOSE Workflow Item -> Browse... button -> New -> Remote) will not save the newly specified connection anywhere on Windows. This issue may be related to secure storage, since ICE on Windows is missing a prompt asking for its which appears in other OS when the dialog is closed.

**Comment by jayjaybillings** [comment]
Probably a question for Greg.


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by ds-ga-1007** [comment]
Is this specific to Windows? I don't have access to a Windows box to test.

**Comment by SmithRWORNL** [comment]
@ds-ga-1007 Yes, I tested on both Mac and Linux and was able to add connections, so it seems to be a Windows only issue.

**Comment by jarrah42** [comment]
Is secure storage working for other plugins?

**Comment by SmithRWORNL** [comment]
@jarrah42 I can't think of any others that make use of it in ICE. There seems to be an org.eclipse.equinox.secure.storage entry that gets automatically populated and empty ones for two other plugins. Is there a way I can test it?

**Comment by SmithRWORNL** [comment]
Deleting my secure storage file and restarting ICE allowed me to successfully add a connection.
