### ISSUE TITLE
On Fedora 25 importing local repository to ICE generated 65 errors

### ISSUE THREAD

**Issue by anarak** [eclipse/ice#319]
One of the errors is about incomplete build path (or simply not referencing it properly). This issue could probably be about misconfigured project.

**Comment by SmithRWORNL** [comment]
We looked at this and it was a problem with using an old version of the repo (from the XSEDE tutorial) with a newer version of ICE. 

Anara, let me know how the new repo works out and I'll close the ticket if there are no further errors.

**Comment by anarak** [comment]
Yes, the newer version of ICE has no problems with the git repo (I cloned it from 'Developer->ICE->Clone') now. Please go ahead and close this ticket. Added notes to #321 for updating tutorial on this issue.

**Comment by jayjaybillings** [comment]
Anara,


You should be able to just hit the close button...


Jay


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by anarak** [comment]
@jayjaybillings, ok! I thought Robert is managing all that.
