### ISSUE TITLE
Path to VisIt incorrectly generated in ICE (Mac OS X)

### ISSUE THREAD

**Issue by scrawfo6** [eclipse/ice#322]
When adding a new VisIt connection, the path automatically generated by ICE is incorrect in Mac OS X.

Path generated: /Applications/VisIt
Path needed: /Applications/VisIt.app/Contents/Resources/bin/

Unless corrected manually, ICE will not connect to VisIt.

ICE version: 2.2.0, Build id: 20161020
VisIt version 2.9.2

![screen shot 2017-01-26 at 3 06 17 pm](https://cloud.githubusercontent.com/assets/22916096/22348258/089bb6f0-e3d9-11e6-942b-0495c50e25c1.png)

**Comment by anarak** [comment]
If that may help, the xsede manual says that the path to VisIt must be entered manually. Users can install VisIt to any location unless they choose a default one,

**Comment by scrawfo6** [comment]
I can certainly change the tutorial to reflect that, but if we go that route then ICE shouldn't autofill that field at all (that is what is confusing to the user). I'm fine with either solution, and I think VisIt (and ParaView) not filling in the application path is more "future proof."

That said, if the path is left blank I think it should throw some sort of message/error as soon as the user hits "Apply" stating that the path is empty and to fill it appropriately.

**Comment by SmithRWORNL** [comment]
There's been discussion in the past about searching for an installation of VisIt/ParaView on the system path or in likely locations, and populating the default path that way. 

We've also been wanting to eventually gut this entire page and replace it with something more advanced (including opening a file dialog to let the user manually find the executable themselves). That ultimately may be what I do, since worrying about typing out system paths has always been a headache.

**Comment by scrawfo6** [comment]
That sounds like a very elegant solution.

**Comment by jayjaybillings** [comment]
@scrawfo6 is correct. We should put bugs in to fix the functionality and then update the tutorial.

If you want to know what I really think... ;-) I hate that whole menu and I think we should rewrite it. A guy who did some contract work for us suggested that a Master-Details layout might work better and I'm inclined to agree. In that scenario the master page would just be the connection number and types (1 - Visit, 2 - Visit, 3 - Paraview) and the details page would be all the remaining parameters. This would let us use a file browser widget to get the executable. (Of course we could use a FileEntry now and eliminate some of this...)

Also, what @SmithRWORNL just said.

**Comment by anarak** [comment]
Currently, in ICE for Linux, the autofilled path is /home/username. Then, if a user hits 'apply' without touching anything, an error message pops up. Just reporting what I saw in the manual and ICE. Anyway, Robert's idea sounds great.

**Comment by anarak** [comment]
When launching VisIt locally a dialog that pops up lets users specify the path to VisIt executable (manually find an executable). This feature is already there, see the first section 'Launch VisIt locally'.

![screenshot from 2017-01-31 17-12-38](https://cloud.githubusercontent.com/assets/25353166/22486858/37a83f0a-e7d9-11e6-9856-b62c7d81d962.png)

**Comment by scrawfo6** [comment]
Isn't that in the ``Visualization Perspective,'' though? It is my understanding that this view is going away. 

Robert and Jay expressed their desire to be able to launch all of this from the ``Project Explorer,'' which was the origin of my bug report.

I already pulled the section of the tutorial that references the screen captured above, per Robert.

Old: https://wiki.eclipse.org/index.php?title=Visualizing_Output_with_ICE&oldid=406468#VisIt

New: https://wiki.eclipse.org/Visualizing_Output_with_ICE#Visualizing_Output

**Comment by SmithRWORNL** [comment]
@scrawfo6 is correct. The issue is the poor UI when setting up connections through the preferences menu leading to problems with people having to type in file paths. We want to redesign that menu entirely, so that we have a single standardized and user friendly way to set up visualization service connections. The Visualization view will eventually be removed entirely.

**Comment by anarak** [comment]
Thank you clarifying, My point was that manual path building (about which @SmithRWORNL was saying) has already been implemented. This is for the purpose of reusing the code that is already there, but of course it's up to @SmithRWORNL.
