### ISSUE TITLE
Develop an app store for scientific software that will sandbox the code in containers

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#324]
Develop a set of new ICE actions that will orchestrate the process of launching a new sandbox version of the OS that will have the scientific software.

**Comment by jayjaybillings** [comment]
"Actions" in ICE have a very specific meaning. They are used by the workflow engine. So I'll clarify what we are looking for here to avoid confusion. 

What we really need for this is a kind of "sub-application" in ICE that is really a standalone thing. It would be launched from the developer menu and pop up its own non-modal dialog just like the Eclipse Marketplace app. Users would select a scientific application or set of applications from this window and possibly a project or two from the workspace, and all of these would be deployed into a Docker container. The user would then be automatically connected to the Docker container using PTP synchronized projects.

**Comment by jayjaybillings** [comment]
Assigned to @amccaskey and I for now since @anarak isn't a committer yet.
