### ISSUE TITLE
Develop wizard user interface (using Balsamiq) to create the sandbox 

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#325]
Wizard user interface (Balsamiq) to create the sandbox 
o	Drop some story boards
o	Activity diagram that shows the flow and
o	GUI in Balsamiq

•	The Wizard forms will need to include the following: 
o	List of packages available
o	Box to choose compilers
o	OS that you want to use
o	Provide an import button on the wizard for a default docker module
o	What ports do you want open in the OS
o	Box for user can select already created image
o	Can I re-connect to an existed container the same environment you worked on yesterday (when pass flag to Docker - - rm)

**Comment by jayjaybillings** [comment]
Assigned to @amccaskey and I for now since @anarak isn't a committer yet.

**Comment by jayjaybillings** [comment]
For now we can do this using pen and paper or a whiteboard. We only need to digitize it before the talk.
