### ISSUE TITLE
Explore calling PTP to create synchronized projects programmatically 

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#326]
Develop PTP to synchronize project sample programmatically (I.e. Use the API instead of the GUI),  
o	we need an API to be able to call.

**Comment by jarrah42** [comment]
To clarify, do you want to be able to create a synchronized project programmatically? I think this is probably already possible, but I would suggest sending an email to the ptp-users list.

**Comment by jayjaybillings** [comment]
@jarrah42 Yes. Once we create the Docker image, we want to create/import a "remote" project from that container.

**Comment by amccaskey** [comment]
This has been done. https://github.com/eclipse/ice/blob/mccaskey/appstore/org.eclipse.ice.developer.apps.impl.eclipse/src/eclipseapps/impl/DockerPTPSyncProjectLauncherImpl.java
