### ISSUE TITLE
Include syntax highlighting 

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#327]
Syntax highlighting is very important for code completion we need to include it,  
o	CDT indexer has to  index the header files inside the directory.
o	(currently Alex uses SSHFS to mount a remote directory locally)

**Comment by jarrah42** [comment]
Syntax highlighting of what? Highlighting of C/C++ code should already be there.

**Comment by jayjaybillings** [comment]
@jarrah42 This is about the Eclipse Converge talk where are building the app store. The idea is that we want to import "remote" projects from the Docker containers after we create them. @amccaskey should correct me if I am wrong, but I think the issuer here is really just about getting the right project nature configured?

**Comment by jayjaybillings** [comment]
Assigned to @amccaskey and I for now since @anarak isn't a committer yet.

**Comment by amccaskey** [comment]
This is done since we use CDT
