### ISSUE TITLE
There is a bug in the synchronized project (PTP does synch via git) when you have git submodules

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#328]
There is a bug in the synchronized project (PTP does synch via git) when you have git submodules

**Comment by jarrah42** [comment]
Please open a bugzilla entry and include a test case if you think there is a bug in PTP.

**Comment by jayjaybillings** [comment]
Thanks @klaskyhb.

@amccaskey Will you please file the bug against PTP or talk to @jarrah42 to make sure it is actually a bug before filing?

Closing since this is a PTP bug.

**Comment by jarrah42** [comment]
I found this bug which may be similar: https://bugs.eclipse.org/bugs/show_bug.cgi?id=493285
