### ISSUE TITLE
Research the best option to use: SWT or SWT plus VAADIN with browser widget

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#331]
Research the best option to use: SWT or SWT plus VAADIN with browser widget, and why.

**Comment by jayjaybillings** [comment]
Assigned to Alex and I for now since @anarak isn't a committer yet.

**Comment by klaskyhb** [comment]
During our meeting today we resolved to use VAADIN for the development of the UI for the Service Scientific Software App Store for Eclipse.  The latter will make it easier to work on a browser when we eventually move ICE to a web service. @anarak and @amccaskey  may like to comment more on this.
