### ISSUE TITLE
Archive or remove the outdated article 

### ISSUE THREAD

**Issue by anarak** [eclipse/ice#332]
This is not relevant anymore:

https://wiki.eclipse.org/Fedora_AMD_Graphics_Drivers

**Comment by SmithRWORNL** [comment]
I would prefer archival. We have a bug on EAVP for adding a jMonkeyEngine implementation of the geometry and mesh services, so in the future this information could be useful to us.

**Comment by jayjaybillings** [comment]
I would just put a big disclaimer at the top that says it is out of date. @scrawfo6 might know how to do such a banner.

**Comment by anarak** [comment]
There is a section 'Legacy Tutorials' in https://wiki.eclipse.org/ICE_Tutorials . Maybe we could move that articl3e to legacy tutorials from https://wiki.eclipse.org/ICE_Developer_Documentation?

**Comment by jayjaybillings** [comment]
+1.

**Comment by scrawfo6** [comment]
I can do that. I will also see about putting a note/banner on it.

**Comment by scrawfo6** [comment]
Done.

Moved the link to the "Legacy Tutorials" section and removed it from the documentation section.

Also, all "Legacy Tutorials" now have a banner (a div w/some CSS).
