### ISSUE TITLE
All 4 buttons in Geometry Editor work intermittently

### ISSUE THREAD

**Issue by anarak** [eclipse/ice#335]
Reset Camera, Zoom to fit, Toggle Axes, Set Axis Size don't work properly in the Geometry Editor whereas right-click buttons Reset Camera and Zoom to fit always work. (on Fedora 25)

**Comment by jayjaybillings** [comment]
I've never had any problems with them, but @anarak is correct that they should work EXACTLY the same.

**Comment by anarak** [comment]
I opened Geometry Editor again later today and on the first attempt, all the buttons worked, but on the second, they didn't work even after making sure that a specific shape selected except the right-click buttons.

**Comment by anarak** [comment]
I opened Geometry Editor again later today and on the first attempt, all the buttons worked, but on the second, they didn't work even after making sure that a specific shape is selected except the right-click buttons.
