### ISSUE TITLE
VisIt is not connecting in ICE properly (Fedora 25)

### ISSUE THREAD

**Issue by anarak** [eclipse/ice#336]
VisIt seems to be loading in the background and never completing it. Attached is the shot of the lower right corner of ICE.
![screenshot from 2017-02-01 16-35-21](https://cloud.githubusercontent.com/assets/25353166/22527307/ab4610ae-e89c-11e6-93d8-ee7d45a8379a.png)

**Comment by anarak** [comment]
To confirm that VisIt is not connecting, in 4.4.2 of xsede tutorial after clicking on 'Add a plot to the list' in VisIt Plot Viewer the following error appeared:
![screenshot from 2017-02-02 09-44-04](https://cloud.githubusercontent.com/assets/25353166/22553986/9100e8f0-e92c-11e6-9328-91cb833e6f68.png)

**Comment by SmithRWORNL** [comment]
This is a problem with VisIt installation, not with ICE per se. 

We need to update the documentation to alert Fedora users who experience this problem that they need to repair their VisIt installation and point them to instructions to do so.

**Comment by anarak** [comment]
The problem was a missing library. It seems to be a common problem with Linux systems. Running `./bin/visit` caused error saying `error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory`. 

Downloading the missing library `sudo yum install libpng12` resolved the problem.

This must be added to the manual and/or added to Fedora image if this lib is not there.
