### ISSUE TITLE
Develop UI forms of using VAADIN in the Scientific Software App Store Service

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#340]
Develop UI forms of using VAADIN in the Scientific Software App Store Service

[2017 Eclipse Converge Talk]

**Comment by anarak** [comment]
Sub-issue: develop Tile View

**Comment by jayjaybillings** [comment]
?Please create a new issue and refer to this one in its description to create a "sub-issue."


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by amccaskey** [comment]
We have a Vaadin view for the app store now.
