### ISSUE TITLE
Add new sub-menu options in ICE to access the scientific software app store service

### ISSUE THREAD

**Issue by klaskyhb** [eclipse/ice#342]
To access the scientific software app store service we need to add new sub-menu options in ICE as follows:

 Developer menu-> Scientific Software->Create New
 Developer menu-> Scientific Software->Open

**Comment by klaskyhb** [comment]
[2017 Eclipse Converge Talk]

**Comment by amccaskey** [comment]
We have this menu option now in mccaskey/appstore
