### ISSUE TITLE
2.2.1 build failing in jboss repository-utils

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#351]
This is caused by an issue with the git plugin for Hudson. When the plugin is configured to use command line tools to clone the repository, it does not configure a remote for the repository. The jboss repository-utils mojo requires the remote in order to operate correctly. The only reference I could find to this was here: https://issues.jenkins-ci.org/browse/JENKINS-21110. Although this is not exactly the same issue, I believe it is caused by the same bug.

The only way I could get the build to work was to switch to using JGit for the checkout. Unfortunately this fails for some other reason, but it at least sets up the git config correctly. After it fails, I switched back to command line git and the build was successful. As long as the hudson workspace is not deleted, this should continue to work.

The reason it works for local builds is that the command used to clone the repo locally will set up the remotes correctly, so the problem does not occur.

**Comment by jayjaybillings** [comment]
@jarrah42 Fixed this.

**Comment by SmithRWORNL** [comment]
@jarrah42 Do you remember what you had to do to get Hudson to use JGit? I'm getting this same error on EAVP, but the "Use command line Git to clone" option gives me the same response whether it's on or off.

**Comment by jarrah42** [comment]
I believe that is the option I used. If it's still failing then it must be a different problem.

**Comment by jayjaybillings** [comment]
If I am not mistake, Greg had to run the build once with JGIT turned off (command line Git only) and then after that it worked with JGIT.


Jay


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________
