### ISSUE TITLE
2.2.1 build is overwriting next build

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#352]
The parent pom.xml for 2.2.1 sets the releaseName property to "next". The property is used as the destination directory for the build, so the next build is being overwritten.

**Comment by jayjaybillings** [comment]
That's really weird... I committed the change to that name myself... hm... I'll take a look.

**Comment by jayjaybillings** [comment]
@SmithRWORNL overwrote it in 9a3d1c1. Robert, will you fix it please?

**Comment by SmithRWORNL** [comment]
Reverted one too many commits when undoing the changes I made try to fix the build.

Reverted the revert with commit b46a70316c65d1c0ff3d7f03f2ce1c7854883600.
