### ISSUE TITLE
Introduce a sample Vaadin bundle and resolve build issues.

### ISSUE THREAD

**Issue by knram06** [eclipse/ice#355]
The aim is

1. To introduce a Vaadin bundle that demonstrates how to connect to a Core instance using OSGi, into the repository.
2. Ensure that the relevant project build properties are updated and ICE builds correctly.

The sample Vaadin app is based on Jay's work in prototyping a Vaadin application to use OSGi services as outlined in:
http://www.jayjaybillings.com/thesis/eclipse/2016/12/14/vaadin-and-osgi.html

This request is from Ram from RNET to support efforts to prototype a web-based interface using ICE.

**Comment by jayjaybillings** [comment]
@amccaskey has a sample bundle of this going at https://github.com/jayjaybillings/thesis/org.eclipse.ice.client.vaadin

![ice-vaadin-2017-03-30](https://cloud.githubusercontent.com/assets/6378849/24523684/e6acf26a-1561-11e7-901e-b182007be69b.png)

@knram06 What else do you need for 1 above? Do you need a completely standalone executable for 2?

**Comment by knram06** [comment]
@jayjaybillings , based on our conversation in the email, I don't think I would be needing anything else right now. Thanks.
