### ISSUE TITLE
Update the MeshComponent for January

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#370]
The current MeshComponent relies on explicit knowledge of EAVP data structures to perform compressed XML persistence. This prevents it from being moved into January. We need to move the responsibility for creating a compressed representation to the IPlot and allow this to be passed up to the component rather than forcing the component to create it itself to allow the MeshComponent into January.

**Comment by jayjaybillings** [comment]
I think we need to completely re-design the MeshComponent or consider dropping the capability entirely. (I am reluctant to do the latter.) For the moment it is sufficient to leave the MeshComponent in an otherwise gutted o.e.i.datastructures bundle.
