### ISSUE TITLE
Proposed updates to Build/Deployment scheme for ICE

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#372]
ICE Devs, 

Will you please tell me what you think about this proposed new build layout for ICE (see picture)? Right now our current build process is murderously monolithic. I feel like breaking it up will let us do two things better:
1) Work on various parts of the code without fussing with the other parts (no more importing all of ICE to work on a few bundles)
2) Carve up the source tree so that we can create new minimal, headless, and Vaadin-based products without creating an even longer and more complicated build.

Any thoughts?

![ice_proposed_build_20170524](https://cloud.githubusercontent.com/assets/6378849/26416717/d94ffb14-4084-11e7-8cf3-5392eb3c575b.jpg)

**Comment by jayjaybillings** [comment]
Basically each "module" of the source tree will get its own aggregator so that it can be built separately, but for those who want to build the whole thing, there will still be an "aggregator of aggregators."

I just realized that I left the target bundle off, but I think that would remain on its own next to o.e.i.parent.

**Comment by jayjaybillings** [comment]
I was just talking to Robert. He said that he likes it overall, but stressed that we need to watch out and make sure we chain the builds right, specifically the tests and product builds.

**Comment by jayjaybillings** [comment]
My other motivation for this is that our individual unit tests no longer run as j-unit plugin tests in Eclipse. I think that is primarily because of bloat.

**Comment by jarrah42** [comment]
Seems like this is more a dependency problem rather than a build problem. If you get the dependencies correct, then the build should drop out pretty easily. In any case, it seems fine to me. Not sure what the "Dev" branch is.

**Comment by jayjaybillings** [comment]
The dev branch is all of our ICE-specific development bundles, like our project generators, app store, and menu extension points API.

What do you mean by drop out?

**Comment by jarrah42** [comment]
I mean once you've got the dependencies right, the build structure should follow pretty naturally.

**Comment by jayjaybillings** [comment]
Oh, yes, agreed: This is as much about cleaning up our dependencies as the build per se.

**Comment by jayjaybillings** [comment]
Closing this as we now have a much simpler build in 3.0.
