### ISSUE TITLE
Target is unresolvable

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#373]
The Oxygen target cannot be resolved. In the site http://download.eclipse.org/releases/oxygen/, there are three errors:

Unable to locate installable unit org.eclipse.ecf.remoteservice.rest.synd.feature.feature.group 0.0.0
Unable to locate installable unit org.eclipse.ecf.remoteservice.sdk.source.feature.feature.group 0.0.0
Unable to locate installable unit org.eclipse.ecf.remoteservice.soap.feature.feature.group 0.0.0

On the mailing list, nobody could justify why these features are in the target and removing them seems to get the target and build working again, so I assume that whatever was in them has been moved to other features in Oxygen and suggest their removal.

**Comment by jayjaybillings** [comment]
To be honest, I just included all of ECF in ICE. If you remove these then we need to make sure that ICE still publishes a remote OSGi service for Ram and the RNET team.

**Comment by jayjaybillings** [comment]
I should be more explicit: I'm fine with you removing these if that is the solution.

**Comment by SmithRWORNL** [comment]
Removed the packages with commit b105b48a51f89f55f466184c2f96f754bf19c518

**Comment by jayjaybillings** [comment]
Will you also confirm that master builds please??


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________
