### ISSUE TITLE
32-bit images should be deprecated

### ISSUE THREAD

**Issue by jarrah42** [eclipse/ice#375]
Is anyone still running 32-bit executables on Linux or Windows? Java 9 will only support 64-bit which means Eclipse will probably follow suit: https://bugs.eclipse.org/bugs/show_bug.cgi?id=526620

**Comment by jayjaybillings** [comment]
?I think we can drop 32bit support. We definitely won't need it for ICE III.


Jay


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________
