### ISSUE TITLE
Create new Commands API

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#384]
@osbornjd and I are creating a new Commands interface for ICE III that will allow for the execution of local and remote commands, to start, and later support extra types of commands. This is the parent issue for creating tasks related to this development.

**Comment by jayjaybillings** [comment]
@osbornjd Would you say we're done with this one? :-D

**Comment by osbornjd** [comment]
@jayjaybillings I'd say so - at this point it is maintenance and/or bug tracking.
