### ISSUE TITLE
FileHandler Design Overhaul

### ISSUE THREAD

**Issue by osbornjd** [eclipse/ice#404]
FileHandler needs to undergo an overhaul in its design. We will have a factory class FileHandlerFactory that gives an abstract FileHandler class. Command should delegate to FileHandler, since FileHandler will have very similar functionality to Command. From FileHandler concrete instances of LocalFileHandler/RemoteFileHandler can be created. 

FileHandler will need its own member variable that is of type Command and its own instance of getStatus since it is not inheriting directly from Command. 

This supports [384](https://github.com/eclipse/ice/issues/384)

**Comment by jayjaybillings** [comment]
Instead of an abstract base class, we should use an IFileHandler Interface because the two implementations will be completely different.
