### ISSUE TITLE
FileBrowser Efficiency

### ISSUE THREAD

**Issue by osbornjd** [eclipse/ice#415]
The FileBrowsing API needs to have a way to test/determine whether or not file trees are walked in an efficient manner, for cases where a directory structure is extremely large. If the FileBrowsing is not efficient, this should be improved.

**Comment by osbornjd** [comment]
For example, right now if a user calls:

```java
FileBrowser.listFiles("/some/directory");
FileBrowser.listDirectories("/some/directory");
```
The FileBrowser will recursively scan through `/some/directory` twice, which is inherently inefficient. Need to come up with a better design to reduce this inefficiency

**Comment by osbornjd** [comment]
This was improved by a factor of 2x in this [PR](https://github.com/eclipse/ice/pull/416)

**Comment by jayjaybillings** [comment]
So good to close?

**Comment by osbornjd** [comment]
@jayjaybillings We can close this for now. The PR improved the efficiency, so in that sense the issue was resolved. However, the question is can the efficiency be further improved (maybe). But I don't know if that is worth leaving an issue open for, because probably the efficiency for all code could be improved and you wouldn't necessarily leave a ticket open for that.
