### ISSUE TITLE
Move Commands Tests Requiring External Resources

### ISSUE THREAD

**Issue by osbornjd** [eclipse/ice#446]
The Commands tests that require external resources need to be moved into the integration test area that @dbluhm recently set up. The tests that need to be moved are all classes that contain tests which contain remote connection requirements. Additionally, tests that require the `EmailUpdateHandler` functionality need to be moved.

This essentially boils down to any test that fails if you check out Commands and try to run `mvn clean verify` straight out of the clone, without setting up any configuration files.

**Comment by dbluhm** [comment]
@osbornjd any further tasks on this issue or are we good to close after #452?

**Comment by jayjaybillings** [comment]
@osbornjd This is done, right?

**Comment by osbornjd** [comment]
@dbluhm already bugged me about it and I apparently missed it a few months ago. This is good to close after #452 was merged.
