### ISSUE TITLE
@DataElement has trouble with enums

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#450]
This is probably low priority, but here's an example of using an @DataElement annotated class with an enumerated value for a member.

```java
@DataElement(name="TaskStateData")
public class TaskStateDataSpec {

	/**
	 * The state of the task
	 */
	@DataField.Default(value = "org.eclipse.ice.tasks.TaskState.INITIALIZED")
	@DataField
	private TaskState taskState;
	
}
```

Note that the full `org.eclipse.ice.tasks.TaskState.INITIALIZED` declaration is required because the `value` tag is a pass through and `import org.eclipse.ice.tasks.TaskState;` is not included.

**Comment by dbluhm** [comment]
Should be fixed now
