### ISSUE TITLE
Using an enumeration with @DataElement causes errors until mvn build is run

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#451]
Declaring an enumeration for the first time in a spec like this in Person.java
```java
	/**
	 * Basic enumeration example. Note that the fully qualified value name needs
	 * to be added and the first time the enumeration is used the build needs
	 * to be run.
	 */
	@DataField.Default(value="org.eclipse.ice.renderer.PersonEnum.TALL");
	@DataField public PersonEnum height;
```
causes the following errors in Eclipse:
```
Multiple markers at this line
	- Syntax error, insert "enum Identifier" to complete 
	 EnumHeaderName
	- Syntax error, insert "EnumBody" to complete EnumDeclaration
```

This appear to resolve after a Maven build.

**Comment by dbluhm** [comment]
This may have been solved by #454 but not positive. I'll see if I can reproduce the problem with those changes merged.

**Comment by dbluhm** [comment]
Ran into this again, did a little more research and found this: https://github.com/jbosstools/m2e-apt/issues/64

Not sure it's the exact issue but I still haven't found a way to mitigate the problem other than just running maven.

**Comment by jayjaybillings** [comment]
Let's consider it fixed.
