### ISSUE TITLE
Update Commands READMEs

### ISSUE THREAD

**Issue by osbornjd** [eclipse/ice#453]
The Commands README should be updated to reflect changes after moving the tests into the integration area.

**Comment by osbornjd** [comment]
The Commands README in the actual source code area needs to be updated too to reflect that the "complicated" tests have been moved to the integration test area.

**Comment by jayjaybillings** [comment]
Was this completed?

**Comment by osbornjd** [comment]
The READMEs were updated in this [commit](https://github.com/eclipse/ice/commit/16360b0f7e3447e08eab6aa47a21d19b96cd17e1#diff-df960d41661da69c66a7273e14051403d0f9ea6bfa2248ab470835b59f89e895), so this is completed.
