### ISSUE TITLE
Migrate or replace BATS capability into ICE

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#475]
We have a request to migrate or replace the capabilities of the Basic Artifact Tracking System (BATS) prototype that I wrote a couple of years ago into ICE. This will add the capability to connect to and publish an RDF API with Apache Jena. 

The BATS repo is at https://github.com/jayjaybillings/bats . The source code in question is roughly ~500 lines and there are a number of utilities that would need to be addressed as well.

The way that I see this, we can do this in one of two ways:
1) Since that code is copyright UT-Battelle, an ORNL staff member can make the necessary changes to conform to our project license, etc. and submit it as a PR.
2) We can reimplement the capability directly in ICE. At first it would be mostly a straight port, but in time it could be an Persisted annotation available for any Data Element.

**Comment by jayjaybillings** [comment]
I heard from @marshallmcdonnell and he said that he prefers option 1 above so that he can learn about the contribution process. I have added @SmithRWORNL as an assignee to this ticket since he is working with Marshall.

@marshallmcdonnell here are the steps to contribute the code:
1. Follow all of the instructions in our [contributing.md](https://github.com/eclipse/ice/blob/next/CONTRIBUTING.md) file to get started. 
2. Create a fork of the ICE repository.
3. Create a fork of BATS and update the license to [the EPL](https://github.com/eclipse/ice/blob/next/LICENSE) and change the license headers in all source and test files to the [EPL header](https://github.com/eclipse/ice/blob/next/org.eclipse.ice.data/src/main/java/org/eclipse/ice/data/ComponentBuilder.java). Make sure that the copyright is still assigned to your organization.
4. Change all package names from gov.ornl.rse.bats to org.eclipse.ice.bats.
5. Copy BATS as a subdirectory into your working copy.
6. Submit your PR and we'll review it.

Any questions, just holler at me!

**Comment by marshallmcdonnell** [comment]
Perfect! Thanks @jayjaybillings!

**Comment by marshallmcdonnell** [comment]
@jayjaybillings so I do have a question. 

For another project (say "project X") to use just the BATS package, how would this look in that other project X?
Specifically, in the pom.xml?

Right now, in the project X pom file, I am able to add BATS via [JitPack](https://jitpack.io/), so just a `mvn install` pulls it in, no extra steps.
Yet, if we move it into ICE, I believe the same thing would actually build _all of ICE_ (I could be wrong since I can provide the "artifactID").

Do you have any thoughts on how I add BATS as a dependency to project X after the migration to ICE?
Thanks!

**Comment by marshallmcdonnell** [comment]
Chatting with @dbluhm and @osbornjd offline, came up with a possible solution!

Looking at an example in the JitPack repository for [multi-module repositories](https://github.com/jitpack/maven-modular), it could be included as long as there is a top-level pom file for the ICE project with the modules listed.

This looks exactly like what is in the [`org.eclipse.ice.build` pom file](https://github.com/eclipse/ice/blob/next/org.eclipse.ice.build/pom.xml). 

Moving this to the top-level seems to make a lot of sense for my use case but not sure how this will affect the project.

Thoughts?

**Comment by marshallmcdonnell** [comment]
Just to comment as well, PR #478 is my first stab at adding BATS to ICE.

**Comment by jayjaybillings** [comment]
Good question! There are two answers:
1) Until we do a release of ICE to Maven Central, it will be as you describe. org.eclipse.ice.build is our top-level pom.
2) Once ICE is in Maven Central, then I think you'll be able to just pull it in directly as a dependency.

**Comment by marshallmcdonnell** [comment]
Okay great, sounds good!

@jayjaybillings do you have any thoughts on if we move the `org.eclipse.ice.build` pom.xml file to the top-level of ICE (above all the org.eclipse.ice.* sub-directories)?

If I understand correctly, `org.eclipse.ice.build` only hosts that pom.xml file, correct?
I think if I use the JitPack method I described above, ICE would need to have that structure (pom at the head of the repo)
There might be a workaround if that top-level pom isn't there, though. I'll look into this if we can't move it.

@dbluhm may have some insights as well, he pointed me towards the JitPack multi-module example!

**Comment by jayjaybillings** [comment]
Yes, I think that is a good idea. IIRC it used to be bigger in 2.x when it was called org.eclipse.ice.aggregator. I would greatly prefer to have it at the top level directory so that I can just checkout and build the whole thing in one go.

**Comment by jayjaybillings** [comment]
This has been merged. Good work and thanks!
