### ISSUE TITLE
VisIt connections do not work with latest version of VisIt client

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#62]
New VisIt connections do not work with latest version of VisIt client. After configuring a new connection and double clicking a file, the service mysteriously fails.

**Comment by kburova** [comment]
Got into the same problem today. When tried to establish connection via 'Preferences->Visualization', it failed. When tried to 'Launch Visit' in Visualization perspective, it froze the whole thing and I had to do force quit.

**Comment by tcpatt** [comment]
For clarity, I believe the latest version refers to VisIt 2.10.
