### ISSUE TITLE
ICE nightlies need "latest" directory

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#63]
The ICE nightly builds at eclipseice.ornl.gov/downloads should have a dedicated directory structure for the latest nightly build so that we can always point to the p2 site. Right now I have to change the address in ICE, but I shouldn't have to.

I think the directory structure should be:

downloads/(un)stable-nightly/latest/p2

in addition to

downloads/(un)stable-nightly/YYYYMMDD/p2

This can be accomplished by setting the Cron job to remove the /latest directory, then "cp -r YYYYMMDD latest" to create the new one. A symlink would work too, I think.

**Comment by amccaskey** [comment]
Updated transfer builds script to copy latest build to the 'latest' directory for both stable and unstable nighty builds. Users can now point to downloads/(un)stable-nightly/latest/p2 to update their ICE installations. 

Closing this ticket.
