### ISSUE TITLE
Create a specialized JobLauncher for interacting with Docker

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#64]
Design an Item (may be a subclass of JobLauncher) that interacts with a Docker daemon to launch applications in a Docker image/container using something like https://github.com/spotify/docker-client (apache license).

**Comment by jayjaybillings** [comment]
I think we need to refactor the code a little. We need to finally add the ActionFactory and split the launcher action into local, remote and Docker actions. We can figure out how to handle remote Docker later.

**Comment by amccaskey** [comment]
This is still ongoing. I have now updated the Item infrastructure and JobLaunchers to use ActionFactory and new Actions. 

Now starting work on DockerComponent which will serve as a specialized MasterDetailsComponent with available images as the Master and a DataComponent that gets Container launch information for each master image.
