### ISSUE TITLE
Wiki's Info about CSV Plot Viewer under 'Visualizing Output w/ ICE"  is wrong

### ISSUE THREAD

**Issue by kburova** [eclipse/ice#68]
Tried to go over CSV tutorial, and information was quite old. 'CSV Plot Viewer' doesn't exist in ICE, so 'Add Plot', 'Select Plot Type', 'Select features for X and Y' options are not there as well.

**Comment by SmithRWORNL** [comment]
The wiki articles ICE Embedded Visualizations and Visualizing Output with ICE have been updated to reflect the CSV plotting capabilities being updated and moved to a different location in ICE. I think that should be all the CSV articles, but if there are others, let me know.
