### ISSUE TITLE
VisIt Connections in the Visualization Perspective

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#70]
As it stands now, even if VisIt connections are persisted and/or connected through the Preferences > Visualization > VisIt view, users still have to click 'Launch VisIt' in the Visualization perspective to create a VisIt connection. 

We should investigate/discuss ways to leverage existing VisIt connections in the Visualization Perspective.

**Comment by jayjaybillings** [comment]
Yeah, definitely. I want to completely redo that perspective.

Jay

From my phone.
________________________________
From: Alex McCaskey
Sent: Friday, December 18, 2015 2:24 PM
To: eclipse/ice
Subject: [ice] VisIt Connections in the Visualization Perspective (#70)



As it stands now, even if VisIt connections are persisted and/or connected through the Preferences > Visualization > VisIt view, users still have to click 'Launch VisIt' in the Visualization perspective to create a VisIt connection.

We should investigate/discuss ways to leverage existing VisIt connections in the Visualization Perspective.

-

**Comment by SmithRWORNL** [comment]
Have you tried to open a VisIt file after opening a connection through Preferences -> Visualization -> VisIt? Using a previous version of VisIt (2.9.1), I get an error message when opening the connection, but can then use it to render a file just fine after waiting a second. It appears ICE is just too fast in throwing up the error dialog, thinking the connection failed when it's actually just waiting to finish.

**Comment by amccaskey** [comment]
Yea I've noticed that. I hate that it says that it's caught an exception. Not sure why it was set up that way. It happens on the PlotGridComposite for the Output Files and Data tab on our JobLaunchers.
