### ISSUE TITLE
JavaFX Implementations and Data Structure Refactoring for ICE Native Visualization Services 

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#72]
The Geometry Editor, Mesh Editor, and Plant view are to be refactored to make use of a single generic modeling structure which will be extended with implementations for JavaFX and JME3 graphics. There are two major subtasks to be achieved:

1) Create a set of data structures based on the agreed upon EMF, MVC-based, model. These generic data types will encompass all parts of all models in ICE's native visualization packages, providing universal pieces such as edges or CSG shapes. These are to include more specific specialized parts for the various services and JavaFX/JME3 implementations for the views and, where necessary, controllers for each part.

2) Create JavaFX implementations for viewing the objects. This is based on the work of Tony McCrary and feature implementation specific data structures to offer all functionality currently made available through ICE's UI, in the same way the JME3 implementations do. 

Task 1) is finished and task 2) requires only the plant view, which will avoid using the actual data structures from task 1) and not be given a full implementation due to disuse of the functionality and forthcoming removal of the Reactor Analyzer which currently houses it.

**Comment by jayjaybillings** [comment]
Please paste a link to this in the 2.2 release candidate bug on Eclipse Bugzilla.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=482170

**Comment by jayjaybillings** [comment]
I don't understand your last paragraph. BTW - the Reactor Analyzer is already gone, except for the plant-level data structures.

Do you mean to say that you need to create an implementation that uses the Plant-level data structures in org.eclipse.ice.reactor.plant? If so, this is what Jordan's previous JME3 implementation did, so I think all you would have to do is convert his code to draw shapes in JME3 to JavaFX.

Also, in your response to the Bugzilla post for our 2.2 RC, you say that you need to implement copy, clone, etc. Is that for number 1 above?

**Comment by SmithRWORNL** [comment]
Ahh, I wasn't sure if it was completely removed or not as of the last update to next.

I technically already have Plant-level data structures in another branch, it's just that it would probably be slightly more time consuming to actually use them than to just break apart the current classes into generic ones with JME3 implementations and create my own extensions with JavaFX implementations. Either way, the code for drawing the shapes is essentially done, it's just a matter of hooking it up to whatever mechanisms are populating the scene graph that is being drawn. 

Yes, in the 2.2 Bugzilla I was talking about extending the  new classes with functionality that was present, but unused, in the old classes, so as to keep the tests testing for the same functionality even as I'm rewriting them.

**Comment by jayjaybillings** [comment]
Give me some concrete examples of what is missing from the new classes that you want to add based on the old. 

Let's clear up some language stuff here. You are NOT done. We only count work as done when ALL the methods have been implemented and tested, not when the core functionality alone works. There is no "essentially done" on this project. When you say to us "I'm done, but only have a few things to clean up," that is precisely what we hear as opposed to "I have more methods to implement and tests to complete, etc."

I'm a big stickler on "done means DONE!," which at one point was part of our developer documentation. I couldn't find it so I've re-added it. It is my fault that you weren't aware of this, but in the future please be mindful of what you are saying how I hear it. I've been frustrated for the past few weeks that you've been "done" but need to keep doing things on this. Now that I know you are not done, we don't have a problem and I might even allocate some more people to help you on this.

**Comment by SmithRWORNL** [comment]
Currently, the build is failing on org.eclipse.ice.datastructures.test, with problems from Edges having the wrong length, and Transformations no longer being loadable from XML, due to now containing a new class which has no JAXB support. Since we were agreed that the modeling data structures don't need persistence for the moment, I'll probably just remove that test (and move the test class to the appropriate new bundle). 

Thus, the only concrete example currently left is, for the sake of consistency, ensuring every subclass of AbstractMeshComponent/AbstractController/AbstractView has its own copy/clone/equals/hashcode methods instead of only the subset I implemented to get the tests running, although once I run the build again and see new packages failing, I may find more that needs to be done.

I'm sorry for being unclear and not drawing a distinction between being "done" with the Geometry/Mesh Editor's user functionality versus being "done" with every component of the code.

**Comment by jayjaybillings** [comment]
I don't think AbstractControllers and AbstractViews need copy/clone/equals/hashCode (remember it is hashCode with a capitol "C" and that the lowercased version is a bug). We only implement these operations for data structures and/or things that need to be persisted, like Items. So, the views and controllers can probably be safely ignored. If you pass me a link to one of them in GitHub, I'll take a peek and let you know.

**Comment by SmithRWORNL** [comment]
The AbstractControllers definitely do, as the model stipulates that users should, to the greatest extent possible, interact only with the controller after passing the mesh component to the controller factory. Thus, clone commands are issued to Controllers, which create clones of their own data members, including the AbstractMeshComponent. I would argue it's the best way to handle the AbstractViews as well. Take the Shape class, below:

https://github.com/eclipse/ice/blob/UnifiedVizRefactor_NoReactor/org.eclipse.ice.viz.service/src/org/eclipse/ice/viz/service/modeling/Shape.java

Currently, it invokes the view's clone() method as it does not have a handle to the factory that made it, and thus has no way of determining how to construct the correct view given the model it has. I don't see a cleaner way of giving it that knowledge, either.

**Comment by jayjaybillings** [comment]
That design is messed up. The data structures should have absolutely no knowledge of the view, so Shape should not need to do anything with the view. If we have Shapes doing that, it is wrong.

It is common for people to draw MVC with a direct dependency between the model and the view, but that is wrong. Proper MVC requires that any updates posted from the model be done through a subject-observer interface, or some comparable mechanism, that does not expose the concrete types of the observers (views) to the subjects (models).

Thus the reason that AbstractShape from the previous implementation

https://github.com/eclipse/ice/blob/master/org.eclipse.ice.viz.service.geometry/src/org/eclipse/ice/viz/service/geometry/shapes/AbstractShape.java

doesn't require knowledge of the view!

**Comment by SmithRWORNL** [comment]
I'm not sure what the the objection is. 

Changes to the model fire updates through its UpdateableSubscriptionManager, which alerts the controller to decide whether or not to invoke the view's refresh method based on the UpdateableSubscriptionType(s) of the message it just received. The controller then provides the view a reference to the model, just long enough for it to finish redrawing itself. At no point should the model ever be receiving a reference to the view. 

You may be getting thrown off by the names, The Model, View, and Controller are, respectively, ShapeComponent, Shape, and ShapeView, not Shape, ShapeController, and ShapeView.

**Comment by jayjaybillings** [comment]
Okay, stop rocking the boat and follow the existing conventions. Under our normal naming conventions - which are based on the standard naming convention in the Java community and should be pretty obvious - these classes would be named ShapeComponent, ShapeController and ShapeView. The convention is simple: if SomeThing is a Thing, name it after that Thing!

Now, I also don't like the name of AbstractMeshComponent because it comes to close to the name of MeshComponent in ICE's data structures, but it doesn't realize the IComponent interface. The problem here is that people are going to assume that it is some sort of component, but it doesn't realize any component interfaces. This will become even more of an issue once we move all of this to EAVP and people start looking for the component definition. Instead, this is just an abstract definition of a Mesh, so call it "AbstractMesh." Now, if you already have something called AbstractMesh, then change the word "Component" to "Entity" or some such thing.

**Comment by SmithRWORNL** [comment]
@jayjaybillings 
We discussed you looking at some of the tests for the new code this morning to help you get familiar with them. I'd suggest reading AbstractControllerTester from org.eclipse.ice.viz.service.modeling.test, since it covers most of the functionality shared between the majority of the new data types.

**Comment by SmithRWORNL** [comment]
This has been implemented and merged into next.
