### ISSUE TITLE
OSGI Services in built executables

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#73]
In the UnifiedVizRefactor_NoReactor branch, OSGI services from my newly added packages are not being consumed in the built executables.  They work when launched through a run configuration, so I assume this is a problem with not having the plug-ins started correctly. I added the plug-ins to the product, but either that wasn't enough or I did it wrong.

**Comment by amccaskey** [comment]
Not sure if this is still going on, but sounds like a problem with your build.properties. Open the MANIFEST file, click the build tab, and make sure that the OSGI-INF folder is checked as part of the build.

**Comment by SmithRWORNL** [comment]
Issue has been resolved in the UnifiedVizRefactor_NoReactor branch. OSGi services from new packages are now starting.
