### ISSUE TITLE
IEntry refactor breaks the SWTBot tests

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/ice#87]
@SmithRWORNL ran the SWTBot tests on the IEntry refactor branch and found that MOOSE Items no longer properly display their status in the Form and that IEntries no longer give the range of valid values (issue #84?).

**Comment by amccaskey** [comment]
It seems like I just need to go in and update the message String. From what Robert reported, sounds like a message is being displayed, but it's not the same as before.
