### ISSUE TITLE
MOOSETester SWTBot test fails on Mac at Save widget

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#89]
The MOOSETester SWTBot test fails at line 86 where it tries to find the button with tooltip marked Save (Ctrl+S). 

I believe this may be happening due to the fact that I'm on a Mac and it might need to be Save (CMD+S) or something like that. 

Robert, will you please test this for yourself on your Mac and fix if necessary?

**Comment by SmithRWORNL** [comment]
Fixed by commit 80e065a3de7fa2b67ff220a20fed58593801435b.
