### ISSUE TITLE
Equinox errors in stable-nightly/latest build on eclipseice.ornl.gov

### ISSUE THREAD

**Issue by arbennett** [eclipse/ice#90]
The linux-x86_64 version of ICE found at http://eclipseice.ornl.gov/downloads/ice/stable-nightly/latest/ has Equinox issues.  They can be seen in several ways:

1. Open the Eclipse Marketplace via `Help -> Eclipse Marketplace...`
2. Try to open the target platform configuration via `Window -> Preferences -> Plug-in Development -> Target Platform`.

These issues are not in newer builds, so updating the `latest` directory with a new build should resolve this issue.

**Comment by amccaskey** [comment]
Fixed the cronjob script that updates the latest directory. Closing this.
