### ISSUE TITLE
Target error when adding Xtext/Xtend

### ISSUE THREAD

**Issue by arbennett** [eclipse/ice#91]
When trying to add Xtext/Xtend to the target definition an error pops up with:
 > You have selected a targe with a newer version than your current Eclipse installation.  This can cause unexpected behaviour in PDE.  Please use a newer version of Eclipse.

Following this, most of the projects are broken due to bundles not resolving correctly.  Notable bundles include org.slf4j and org.eclipse.platform, among many others.

Both the Xtext/Xtend libraries being added are from download.eclipse.org/releases/mars.

**Comment by arbennett** [comment]
@jayjaybillings This has been solved recently, correct?

**Comment by jayjaybillings** [comment]
I think this has been solved. @arbennett is this still a problem for you?

**Comment by arbennett** [comment]
This is not a problem for me anymore.  Thanks for closing.
