### ISSUE TITLE
MOOSE Workflow tree is not populated on Windows

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/ice#94]
On Windows, the MOOSE Workflow will not populate the MOOSE Tree in the Input Data -- Tree View when the Item is saved. This bug occurs for all MOOSE applications and regardless of whether the application is local or remote to the ICE instance. 

Edit: This bug is also affecting Linux, but not Mac.

**Comment by jayjaybillings** [comment]
Assigned to Alex. This is kind of his baby.

**Comment by amccaskey** [comment]
Interesting find - I just downloaded master latest build, and started ICE in a new workspace, and the workspace path had a space in it. The tree did not load. 

I switched to a workspace that had no spaces in the path name, and the tree did load... 

Looks like I've found the place to start looking.

**Comment by jayjaybillings** [comment]
Hm. That type of bug normally happens when you are opening a file incorrectly. If you look at the way we open files in Data Structures, that is (usually) the safe way to open files with spaces in the path.

**Comment by jayjaybillings** [comment]
That is to say, it might not be that the view is messed up, but that you aren't actually loading the tree from file at all.

**Comment by amccaskey** [comment]
That's what it looks like. Previous implementation of MOOSEModel.createCleanMooseFile is using java nio Files.
