### ISSUE TITLE
ICE Next Product Broken

### ISSUE THREAD

**Issue by amccaskey** [eclipse/ice#97]
I just pulled down the latest next build for both Mac and Linux, and none of the ICE-specific stuff is there. No ICE or MOOSE perspective, no create new Item wizard, etc... 

Looking into next's product file. Looks like org.eclipse.ice.dependencies was still in there, looking into it.

**Comment by amccaskey** [comment]
Fixed with 3b1c1e21686b5a6816d82b72584a4b20f146b4a4 (possibly, need to test habilis builds)

**Comment by amccaskey** [comment]
So even though a local build of ICE Next on my Mac produces a binary that works fine, the latest downloads from eclipseice.ornl.gov are still broken, and I'm not sure why.

**Comment by amccaskey** [comment]
Output on Habilis (notice it's missing the [INFO] Eclipse ICE Build Aggregator ....................... SUCCESS [  0.001 s](

[INFO] --- tycho-p2-director-plugin:0.23.0:archive-products (archive-products) @ org.eclipse.ice.repository ---
[INFO] Building zip: /var/lib/hudson/jobs/ICE Build - Next/workspace/ice/org.eclipse.ice.repository/target/products/ice.product-linux.gtk.x86.zip

[INFO] Building zip: /var/lib/hudson/jobs/ICE Build - Next/workspace/ice/org.eclipse.ice.repository/target/products/ice.product-linux.gtk.x86_64.zip

[INFO] Building zip: /var/lib/hudson/jobs/ICE Build - Next/workspace/ice/org.eclipse.ice.repository/target/products/ice.product-win32.win32.x86.zip

[INFO] Building zip: /var/lib/hudson/jobs/ICE Build - Next/workspace/ice/org.eclipse.ice.repository/target/products/ice.product-win32.win32.x86_64.zip

[INFO] Building zip: /var/lib/hudson/jobs/ICE Build - Next/workspace/ice/org.eclipse.ice.repository/target/products/ice.product-macosx.cocoa.x86_64.zip

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.eclipse.ice.build ............................. SUCCESS [0.347s]
[INFO] org.eclipse.ice.target.mars ....................... SUCCESS [0.090s]
[INFO] org.eclipse.ice.dependencies ...................... SUCCESS [3.015s]
[INFO] org.eclipse.ice.viz.service ....................... SUCCESS [2.798s]
[INFO] org.eclipse.ice.datastructures .................... SUCCESS [0.682s]
[INFO] org.eclipse.ice.client.compatibility .............. SUCCESS [0.120s]
[INFO] org.eclipse.ice.io ................................ SUCCESS [0.368s]
[INFO] org.eclipse.ice.materials ......................... SUCCESS [0.262s]
[INFO] org.eclipse.ice.viz.service.mesh .................. SUCCESS [0.399s]
[INFO] org.eclipse.ice.item .............................. SUCCESS [0.884s]
[INFO] org.eclipse.ice.core .............................. SUCCESS [0.352s]
[INFO] org.eclipse.ice.client ............................ SUCCESS [0.642s]
[INFO] org.eclipse.ice.viz.service.geometry .............. SUCCESS [0.368s]
[INFO] org.eclipse.ice.client.widgets .................... SUCCESS [1.128s]
[INFO] org.eclipse.ice.client.test ....................... SUCCESS [17.339s]
[INFO] org.eclipse.ice.persistence.xml ................... SUCCESS [0.246s]
[INFO] org.eclipse.ice.viz.service.javafx ................ SUCCESS [0.455s]
[INFO] org.eclipse.ice.viz.service.javafx.geometry ....... SUCCESS [0.398s]
[INFO] org.eclipse.ice.reactor.plant ..................... SUCCESS [0.336s]
[INFO] org.eclipse.ice.client.widgets.moose .............. SUCCESS [0.637s]
[INFO] org.eclipse.ice.vibe .............................. SUCCESS [0.266s]
[INFO] org.eclipse.ice.persistence.xml.test .............. SUCCESS [31.222s]
[INFO] org.eclipse.ice.client.widgets.moose.test ......... SUCCESS [0.216s]
[INFO] org.eclipse.ice.client.widgets.test.utils ......... SUCCESS [0.355s]
[INFO] org.eclipse.ice.client.widgets.test ............... SUCCESS [26.134s]
[INFO] org.eclipse.ice.client.rcp ........................ SUCCESS [0.302s]
[INFO] org.eclipse.ice.datastructures.test ............... SUCCESS [20.499s]
[INFO] org.eclipse.ice.developer ......................... SUCCESS [0.425s]
[INFO] org.eclipse.ice.developer.moose ................... SUCCESS [0.496s]
[INFO] org.eclipse.ice.core.test ......................... SUCCESS [5.921s]
[INFO] org.eclipse.ice.item.test ......................... SUCCESS [19.078s]
[INFO] org.eclipse.ice.io.test ........................... SUCCESS [3.852s]
[INFO] org.eclipse.ice.reactor.plant.test ................ SUCCESS [12.248s]
[INFO] org.eclipse.ice.vibe.test ......................... SUCCESS [5.608s]
[INFO] org.eclipse.ice.proteus ........................... SUCCESS [0.224s]
[INFO] org.eclipse.ice.proteus.test ...................... SUCCESS [6.955s]
[INFO] org.eclipse.ice.mesh .............................. SUCCESS [0.196s]
[INFO] org.eclipse.ice.mesh.test ......................... SUCCESS [5.077s]
[INFO] org.eclipse.ice.nek5000 ........................... SUCCESS [0.377s]
[INFO] org.eclipse.ice.nek5000.test ...................... SUCCESS [7.443s]
[INFO] org.eclipse.ice.viz ............................... SUCCESS [0.428s]
[INFO] org.eclipse.ice.viz.test .......................... SUCCESS [5.256s]
[INFO] org.eclipse.ice.viz.service.test .................. SUCCESS [1:39.915s]
[INFO] org.eclipse.ice.viz.service.visit ................. SUCCESS [0.343s]
[INFO] org.eclipse.ice.viz.service.geometry.test ......... SUCCESS [9.116s]
[INFO] org.eclipse.ice.viz.service.javafx.test ........... SUCCESS [0.320s]
[INFO] org.eclipse.ice.viz.service.javafx.mesh ........... SUCCESS [0.330s]
[INFO] org.eclipse.ice.viz.service.mesh.test ............. SUCCESS [5.977s]
[INFO] org.eclipse.ice.viz.service.visit.test ............ SUCCESS [4.809s]
[INFO] org.eclipse.ice.viz.service.paraview.web .......... SUCCESS [0.168s]
[INFO] org.eclipse.ice.viz.service.paraview .............. SUCCESS [0.345s]
[INFO] org.eclipse.ice.viz.service.paraview.test ......... SUCCESS [10.869s]
[INFO] org.eclipse.ice.materials.test .................... SUCCESS [3.747s]
[INFO] org.eclipse.ice.materials.ui ...................... SUCCESS [0.393s]
[INFO] org.eclipse.ice.caebat.batml ...................... SUCCESS [0.253s]
[INFO] org.eclipse.ice.caebat.batml.test ................. SUCCESS [10.863s]
[INFO] org.eclipse.ice.reflectivity ...................... SUCCESS [0.292s]
[INFO] org.eclipse.ice.reflectivity.ui ................... SUCCESS [0.369s]
[INFO] org.eclipse.ice.reflectivity.test ................. SUCCESS [6.864s]
[INFO] org.eclipse.ice.projectgeneration ................. SUCCESS [0.295s]
[INFO] org.eclipse.ice.projectgeneration.test ............ SUCCESS [25.143s]
[INFO] ICE Feature ....................................... SUCCESS [0.444s]
[INFO] ICE Advanced Materials Feature .................... SUCCESS [0.122s]
[INFO] ICE Infrastructure Product ........................ SUCCESS [3:57.974s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:45.399s
[INFO] Finished at: Tue Feb 16 11:49:41 EST 2016

[INFO] Final Memory: 261M/5967M
[INFO] ------------------------------------------------------------------------

**Comment by amccaskey** [comment]
looks like pom file was set incorrectly in Advanced section of maven execution

**Comment by jayjaybillings** [comment]
Which pom file?
